
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.aotain.smmsapi.task.client.cxf;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-12-23T11:24:45.417+08:00
 * Generated source version: 3.0.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "commandack",
                      portName = "commandackHttpPort",
                      targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com",
                      wsdlLocation = "http://60.29.111.230:7777/DataCenter_New/IDCWebService/commandack?wsdl",
                      endpointInterface = "com.aotain.smmsapi.task.client.cxf.CommandackPortType")
                      
public class commandackHttpPortImpl implements CommandackPortType {

    private static final Logger LOG = Logger.getLogger(commandackHttpPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.aotain.smmsapi.task.client.cxf.CommandackPortType#discoveryData(java.lang.String  in0 ,)java.lang.String  in1 )*
     */
    public java.lang.String discoveryData(java.lang.String in0,java.lang.String in1) { 
        LOG.info("Executing operation discoveryData");
        System.out.println(in0);
        System.out.println(in1);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.aotain.smmsapi.task.client.cxf.CommandackPortType#subDomainToday(*
     */
    public java.lang.String subDomainToday() { 
        LOG.info("Executing operation subDomainToday");
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.aotain.smmsapi.task.client.cxf.CommandackPortType#idcCommandack(java.lang.String  in0 ,)java.lang.String  in1 ,)java.lang.String  in2 ,)java.lang.String  in3 ,)java.lang.String  in4 ,)int  in5 ,)int  in6 ,)int  in7 ,)java.lang.String  in8 )*
     */
    public java.lang.String idcCommandack(java.lang.String in0,java.lang.String in1,java.lang.String in2,java.lang.String in3,java.lang.String in4,int in5,int in6,int in7,java.lang.String in8) { 
        LOG.info("Executing operation idcCommandack");
        System.out.println(in0);
        System.out.println(in1);
        System.out.println(in2);
        System.out.println(in3);
        System.out.println(in4);
        System.out.println(in5);
        System.out.println(in6);
        System.out.println(in7);
        System.out.println(in8);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.aotain.smmsapi.task.client.cxf.CommandackPortType#trafficWarning(java.lang.Long  in0 ,)java.lang.Long  in1 ,)java.lang.Long  in2 ,)java.lang.String  in3 )*
     */
    public java.lang.String trafficWarning(java.lang.Long in0,java.lang.Long in1,java.lang.Long in2,java.lang.String in3) { 
        LOG.info("Executing operation trafficWarning");
        System.out.println(in0);
        System.out.println(in1);
        System.out.println(in2);
        System.out.println(in3);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.aotain.smmsapi.task.client.cxf.CommandackPortType#idcCommandackProvince(java.lang.Long  in0 ,)java.lang.String  in1 ,)java.lang.String  in2 ,)java.lang.String  in3 ,)java.lang.String  in4 ,)int  in5 ,)int  in6 ,)int  in7 ,)java.lang.String  in8 )*
     */
    public java.lang.String idcCommandackProvince(java.lang.Long in0,java.lang.String in1,java.lang.String in2,java.lang.String in3,java.lang.String in4,int in5,int in6,int in7,java.lang.String in8) { 
        LOG.info("Executing operation idcCommandackProvince");
        System.out.println(in0);
        System.out.println(in1);
        System.out.println(in2);
        System.out.println(in3);
        System.out.println(in4);
        System.out.println(in5);
        System.out.println(in6);
        System.out.println(in7);
        System.out.println(in8);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.aotain.smmsapi.task.client.cxf.CommandackPortType#selTopDomain(*
     */
    public java.lang.String selTopDomain() { 
        LOG.info("Executing operation selTopDomain");
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.aotain.smmsapi.task.client.cxf.CommandackPortType#subDomainLimit(java.lang.Long  in0 ,)java.lang.Long  in1 )*
     */
    public java.lang.String subDomainLimit(java.lang.Long in0,java.lang.Long in1) { 
        LOG.info("Executing operation subDomainLimit");
        System.out.println(in0);
        System.out.println(in1);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.aotain.smmsapi.task.client.cxf.CommandackPortType#isolationRelease(java.lang.String  in0 ,)java.lang.String  in1 ,)java.lang.String  in2 ,)java.lang.String  in3 ,)java.lang.String  in4 ,)java.lang.Long  in5 ,)java.lang.Long  in6 )*
     */
    public java.lang.String isolationRelease(java.lang.String in0,java.lang.String in1,java.lang.String in2,java.lang.String in3,java.lang.String in4,java.lang.Long in5,java.lang.Long in6) { 
        LOG.info("Executing operation isolationRelease");
        System.out.println(in0);
        System.out.println(in1);
        System.out.println(in2);
        System.out.println(in3);
        System.out.println(in4);
        System.out.println(in5);
        System.out.println(in6);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.aotain.smmsapi.task.client.cxf.CommandackPortType#custom(java.lang.String  in0 ,)java.lang.String  in1 ,)java.lang.String  in2 ,)java.lang.String  in3 ,)java.lang.String  in4 ,)java.lang.Long  in5 )*
     */
    public java.lang.String custom(java.lang.String in0,java.lang.String in1,java.lang.String in2,java.lang.String in3,java.lang.String in4,java.lang.Long in5) { 
        LOG.info("Executing operation custom");
        System.out.println(in0);
        System.out.println(in1);
        System.out.println(in2);
        System.out.println(in3);
        System.out.println(in4);
        System.out.println(in5);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.aotain.smmsapi.task.client.cxf.CommandackPortType#bigScreen(java.lang.String  in0 )*
     */
    public java.lang.String bigScreen(java.lang.String in0) { 
        LOG.info("Executing operation bigScreen");
        System.out.println(in0);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
