package com.aotain.smmsapi.task.client.cxf1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2015-07-14T11:09:19.636+08:00
 * Generated source version: 2.7.12
 * 
 */
@WebService(targetNamespace = "http://webservice.ismi.surfilter.com/", name = "IdcWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface IdcWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "idc_commandack", targetNamespace = "http://webservice.ismi.surfilter.com/", className = "com.aotain.smmsapi.task.client.cxf1.IdcCommandack")
    @WebMethod(operationName = "idc_commandack", action = "http://webservice.ismi.surfilter.com/idc_commandack")
    @ResponseWrapper(localName = "idc_commandackResponse", targetNamespace = "http://webservice.ismi.surfilter.com/", className = "com.aotain.smmsapi.task.client.cxf1.IdcCommandackResponse")
    public java.lang.String idcCommandack(
        @WebParam(name = "idcId", targetNamespace = "http://webservice.ismi.surfilter.com/")
        java.lang.String idcId,
        @WebParam(name = "randVal", targetNamespace = "http://webservice.ismi.surfilter.com/")
        java.lang.String randVal,
        @WebParam(name = "pwdHash", targetNamespace = "http://webservice.ismi.surfilter.com/")
        java.lang.String pwdHash,
        @WebParam(name = "result", targetNamespace = "http://webservice.ismi.surfilter.com/")
        java.lang.String result,
        @WebParam(name = "resultHash", targetNamespace = "http://webservice.ismi.surfilter.com/")
        java.lang.String resultHash,
        @WebParam(name = "encryptAlgorithm", targetNamespace = "http://webservice.ismi.surfilter.com/")
        int encryptAlgorithm,
        @WebParam(name = "hashAlgorithm", targetNamespace = "http://webservice.ismi.surfilter.com/")
        int hashAlgorithm,
        @WebParam(name = "compressionFormat", targetNamespace = "http://webservice.ismi.surfilter.com/")
        int compressionFormat,
        @WebParam(name = "commandVersion", targetNamespace = "http://webservice.ismi.surfilter.com/")
        java.lang.String commandVersion
    );
}
