package com.aotain.smmsapi.task.client.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-12-23T11:24:45.446+08:00
 * Generated source version: 3.0.0
 * 
 */
@WebService(targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com", name = "commandackPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface CommandackPortType {

    @WebResult(name = "out", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
    @RequestWrapper(localName = "discoveryData", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com", className = "com.aotain.smmsapi.task.client.cxf.DiscoveryData")
    @WebMethod
    @ResponseWrapper(localName = "discoveryDataResponse", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com", className = "com.aotain.smmsapi.task.client.cxf.DiscoveryDataResponse")
    public java.lang.String discoveryData(
        @WebParam(name = "in0", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
        java.lang.String in1
    );

    @WebResult(name = "out", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
    @RequestWrapper(localName = "subDomainToday", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com", className = "com.aotain.smmsapi.task.client.cxf.SubDomainToday")
    @WebMethod
    @ResponseWrapper(localName = "subDomainTodayResponse", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com", className = "com.aotain.smmsapi.task.client.cxf.SubDomainTodayResponse")
    public java.lang.String subDomainToday();

    @WebResult(name = "out", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
    @RequestWrapper(localName = "idc_commandack", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com", className = "com.aotain.smmsapi.task.client.cxf.IdcCommandack")
    @WebMethod(operationName = "idc_commandack")
    @ResponseWrapper(localName = "idc_commandackResponse", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com", className = "com.aotain.smmsapi.task.client.cxf.IdcCommandackResponse")
    public java.lang.String idcCommandack(
        @WebParam(name = "in0", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
        java.lang.String in2,
        @WebParam(name = "in3", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
        java.lang.String in3,
        @WebParam(name = "in4", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
        java.lang.String in4,
        @WebParam(name = "in5", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
        int in5,
        @WebParam(name = "in6", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
        int in6,
        @WebParam(name = "in7", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
        int in7,
        @WebParam(name = "in8", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
        java.lang.String in8
    );

    @WebResult(name = "out", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
    @RequestWrapper(localName = "trafficWarning", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com", className = "com.aotain.smmsapi.task.client.cxf.TrafficWarning")
    @WebMethod
    @ResponseWrapper(localName = "trafficWarningResponse", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com", className = "com.aotain.smmsapi.task.client.cxf.TrafficWarningResponse")
    public java.lang.String trafficWarning(
        @WebParam(name = "in0", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
        java.lang.Long in0,
        @WebParam(name = "in1", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
        java.lang.Long in1,
        @WebParam(name = "in2", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
        java.lang.Long in2,
        @WebParam(name = "in3", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
        java.lang.String in3
    );

    @WebResult(name = "out", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
    @RequestWrapper(localName = "idc_commandack_province", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com", className = "com.aotain.smmsapi.task.client.cxf.IdcCommandackProvince")
    @WebMethod(operationName = "idc_commandack_province")
    @ResponseWrapper(localName = "idc_commandack_provinceResponse", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com", className = "com.aotain.smmsapi.task.client.cxf.IdcCommandackProvinceResponse")
    public java.lang.String idcCommandackProvince(
        @WebParam(name = "in0", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
        java.lang.Long in0,
        @WebParam(name = "in1", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
        java.lang.String in2,
        @WebParam(name = "in3", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
        java.lang.String in3,
        @WebParam(name = "in4", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
        java.lang.String in4,
        @WebParam(name = "in5", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
        int in5,
        @WebParam(name = "in6", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
        int in6,
        @WebParam(name = "in7", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
        int in7,
        @WebParam(name = "in8", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
        java.lang.String in8
    );

    @WebResult(name = "out", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
    @RequestWrapper(localName = "selTopDomain", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com", className = "com.aotain.smmsapi.task.client.cxf.SelTopDomain")
    @WebMethod
    @ResponseWrapper(localName = "selTopDomainResponse", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com", className = "com.aotain.smmsapi.task.client.cxf.SelTopDomainResponse")
    public java.lang.String selTopDomain();

    @WebResult(name = "out", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
    @RequestWrapper(localName = "subDomainLimit", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com", className = "com.aotain.smmsapi.task.client.cxf.SubDomainLimit")
    @WebMethod
    @ResponseWrapper(localName = "subDomainLimitResponse", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com", className = "com.aotain.smmsapi.task.client.cxf.SubDomainLimitResponse")
    public java.lang.String subDomainLimit(
        @WebParam(name = "in0", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
        java.lang.Long in0,
        @WebParam(name = "in1", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
        java.lang.Long in1
    );

    @WebResult(name = "out", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
    @RequestWrapper(localName = "isolationRelease", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com", className = "com.aotain.smmsapi.task.client.cxf.IsolationRelease")
    @WebMethod
    @ResponseWrapper(localName = "isolationReleaseResponse", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com", className = "com.aotain.smmsapi.task.client.cxf.IsolationReleaseResponse")
    public java.lang.String isolationRelease(
        @WebParam(name = "in0", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
        java.lang.String in2,
        @WebParam(name = "in3", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
        java.lang.String in3,
        @WebParam(name = "in4", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
        java.lang.String in4,
        @WebParam(name = "in5", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
        java.lang.Long in5,
        @WebParam(name = "in6", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
        java.lang.Long in6
    );

    @WebResult(name = "out", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
    @RequestWrapper(localName = "custom", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com", className = "com.aotain.smmsapi.task.client.cxf.Custom")
    @WebMethod
    @ResponseWrapper(localName = "customResponse", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com", className = "com.aotain.smmsapi.task.client.cxf.CustomResponse")
    public java.lang.String custom(
        @WebParam(name = "in0", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
        java.lang.String in2,
        @WebParam(name = "in3", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
        java.lang.String in3,
        @WebParam(name = "in4", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
        java.lang.String in4,
        @WebParam(name = "in5", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
        java.lang.Long in5
    );

    @WebResult(name = "out", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
    @RequestWrapper(localName = "bigScreen", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com", className = "com.aotain.smmsapi.task.client.cxf.BigScreen")
    @WebMethod
    @ResponseWrapper(localName = "bigScreenResponse", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com", className = "com.aotain.smmsapi.task.client.cxf.BigScreenResponse")
    public java.lang.String bigScreen(
        @WebParam(name = "in0", targetNamespace = "http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com")
        java.lang.String in0
    );
}
