
package com.aotain.smmsapi.task.client.cxf.tj;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2015-12-29T12:41:40.929+08:00
 * Generated source version: 2.7.12
 * 
 */
public final class CommandackPortType_CommandackHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://company.service.webservice.smms.ncs.com", "commandack");

    private CommandackPortType_CommandackHttpPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Commandack.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Commandack ss = new Commandack(wsdlURL, SERVICE_NAME);
        CommandackPortType port = ss.getCommandackHttpPort();  
        
        {
        System.out.println("Invoking idcCommandack...");
        java.lang.String _idcCommandack_in0 = "";
        java.lang.String _idcCommandack_in1 = "";
        java.lang.String _idcCommandack_in2 = "";
        java.lang.String _idcCommandack_in3 = "";
        java.lang.String _idcCommandack_in4 = "";
        java.lang.Integer _idcCommandack_in5 = null;
        java.lang.Integer _idcCommandack_in6 = null;
        java.lang.Integer _idcCommandack_in7 = null;
        java.lang.String _idcCommandack_in8 = "";
        java.lang.String _idcCommandack__return = port.idcCommandack(_idcCommandack_in0, _idcCommandack_in1, _idcCommandack_in2, _idcCommandack_in3, _idcCommandack_in4, _idcCommandack_in5, _idcCommandack_in6, _idcCommandack_in7, _idcCommandack_in8);
        System.out.println("idcCommandack.result=" + _idcCommandack__return);


        }

        System.exit(0);
    }

}
