//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.14 at 02:35:40 下午 CST 
//


package com.aotain.smmsapi.task.bean;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="commandId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="idcId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="houseId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="urlCategory" type="{http://www.w3.org/2001/XMLSchema}long" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="urlCategoryControl" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="ipRangeStr" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *         &lt;element name="ipRangeControl" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="portRangeStr" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *         &lt;element name="portRangeControl" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="appType" type="{http://www.w3.org/2001/XMLSchema}long" maxOccurs="unbounded"/>
 *         &lt;element name="appControl" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="proType" type="{http://www.w3.org/2001/XMLSchema}long" maxOccurs="unbounded"/>
 *         &lt;element name="protocolControl" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="effectTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="expiredTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="operationType" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="timeStamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "commandId",
    "idcId",
    "houseId",
    "urlCategory",
    "urlCategoryControl",
    "ipRangeStr",
    "ipRangeControl",
    "portRangeStr",
    "portRangeControl",
    "appType",
    "appControl",
    "proType",
    "protocolControl",
    "effectTime",
    "expiredTime",
    "operationType",
    "timeStamp"
})
@XmlRootElement(name = "areaControlPolicy")
public class AreaControlPolicy {

    protected long commandId;
    @XmlElement(required = true)
    protected String idcId;
    protected long houseId;
    @XmlElement(type = Long.class)
    protected List<Long> urlCategory;
    protected long urlCategoryControl;
    @XmlElement(required = true)
    protected List<String> ipRangeStr;
    protected long ipRangeControl;
    @XmlElement(required = true)
    protected List<String> portRangeStr;
    protected long portRangeControl;
    @XmlElement(type = Long.class)
    protected List<Long> appType;
    protected long appControl;
    @XmlElement(type = Long.class)
    protected List<Long> proType;
    protected long protocolControl;
    @XmlElement(required = true)
    protected String effectTime;
    @XmlElement(required = true)
    protected String expiredTime;
    protected long operationType;
    @XmlElement(required = true)
    protected String timeStamp;

    /**
     * Gets the value of the commandId property.
     * 
     */
    public long getCommandId() {
        return commandId;
    }

    /**
     * Sets the value of the commandId property.
     * 
     */
    public void setCommandId(long value) {
        this.commandId = value;
    }

    /**
     * Gets the value of the idcId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdcId() {
        return idcId;
    }

    /**
     * Sets the value of the idcId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdcId(String value) {
        this.idcId = value;
    }

    /**
     * Gets the value of the houseId property.
     * 
     */
    public long getHouseId() {
        return houseId;
    }

    /**
     * Sets the value of the houseId property.
     * 
     */
    public void setHouseId(long value) {
        this.houseId = value;
    }

    /**
     * Gets the value of the urlCategory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the urlCategory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUrlCategory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Long }
     * 
     * 
     */
    public List<Long> getUrlCategory() {
        if (urlCategory == null) {
            urlCategory = new ArrayList<Long>();
        }
        return this.urlCategory;
    }

    /**
     * Gets the value of the urlCategoryControl property.
     * 
     */
    public long getUrlCategoryControl() {
        return urlCategoryControl;
    }

    /**
     * Sets the value of the urlCategoryControl property.
     * 
     */
    public void setUrlCategoryControl(long value) {
        this.urlCategoryControl = value;
    }

    /**
     * Gets the value of the ipRangeStr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ipRangeStr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIpRangeStr().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getIpRangeStr() {
        if (ipRangeStr == null) {
            ipRangeStr = new ArrayList<String>();
        }
        return this.ipRangeStr;
    }

    /**
     * Gets the value of the ipRangeControl property.
     * 
     */
    public long getIpRangeControl() {
        return ipRangeControl;
    }

    /**
     * Sets the value of the ipRangeControl property.
     * 
     */
    public void setIpRangeControl(long value) {
        this.ipRangeControl = value;
    }

    /**
     * Gets the value of the portRangeStr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the portRangeStr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPortRangeStr().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPortRangeStr() {
        if (portRangeStr == null) {
            portRangeStr = new ArrayList<String>();
        }
        return this.portRangeStr;
    }

    /**
     * Gets the value of the portRangeControl property.
     * 
     */
    public long getPortRangeControl() {
        return portRangeControl;
    }

    /**
     * Sets the value of the portRangeControl property.
     * 
     */
    public void setPortRangeControl(long value) {
        this.portRangeControl = value;
    }

    /**
     * Gets the value of the appType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the appType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAppType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Long }
     * 
     * 
     */
    public List<Long> getAppType() {
        if (appType == null) {
            appType = new ArrayList<Long>();
        }
        return this.appType;
    }

    /**
     * Gets the value of the appControl property.
     * 
     */
    public long getAppControl() {
        return appControl;
    }

    /**
     * Sets the value of the appControl property.
     * 
     */
    public void setAppControl(long value) {
        this.appControl = value;
    }

    /**
     * Gets the value of the proType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the proType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Long }
     * 
     * 
     */
    public List<Long> getProType() {
        if (proType == null) {
            proType = new ArrayList<Long>();
        }
        return this.proType;
    }

    /**
     * Gets the value of the protocolControl property.
     * 
     */
    public long getProtocolControl() {
        return protocolControl;
    }

    /**
     * Sets the value of the protocolControl property.
     * 
     */
    public void setProtocolControl(long value) {
        this.protocolControl = value;
    }

    /**
     * Gets the value of the effectTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEffectTime() {
        return effectTime;
    }

    /**
     * Sets the value of the effectTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEffectTime(String value) {
        this.effectTime = value;
    }

    /**
     * Gets the value of the expiredTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpiredTime() {
        return expiredTime;
    }

    /**
     * Sets the value of the expiredTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpiredTime(String value) {
        this.expiredTime = value;
    }

    /**
     * Gets the value of the operationType property.
     * 
     */
    public long getOperationType() {
        return operationType;
    }

    /**
     * Sets the value of the operationType property.
     * 
     */
    public void setOperationType(long value) {
        this.operationType = value;
    }

    /**
     * Gets the value of the timeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeStamp() {
        return timeStamp;
    }

    /**
     * Sets the value of the timeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeStamp(String value) {
        this.timeStamp = value;
    }

}
