package com.aotain.smmsapi.task.client.cxf1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2015-07-14T11:09:19.677+08:00
 * Generated source version: 2.7.12
 * 
 */
@WebServiceClient(name = "IDCWebService", 
                  wsdlLocation = "http://183.136.190.57:7080/ism/ws/commandack?wsdl",
                  targetNamespace = "http://webservice.ismi.surfilter.com/") 
public class IDCWebService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.ismi.surfilter.com/", "IDCWebService");
    public final static QName IdcWebServicePort = new QName("http://webservice.ismi.surfilter.com/", "IdcWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://183.136.190.57:7080/ism/ws/commandack?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IDCWebService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://183.136.190.57:7080/ism/ws/commandack?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IDCWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IDCWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IDCWebService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IDCWebService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IDCWebService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IDCWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IdcWebService
     */
    @WebEndpoint(name = "IdcWebServicePort")
    public IdcWebService getIdcWebServicePort() {
        return super.getPort(IdcWebServicePort, IdcWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IdcWebService
     */
    @WebEndpoint(name = "IdcWebServicePort")
    public IdcWebService getIdcWebServicePort(WebServiceFeature... features) {
        return super.getPort(IdcWebServicePort, IdcWebService.class, features);
    }

}
