//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.14 at 02:35:40 下午 CST 
//


package com.aotain.smmsapi.task.bean;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idcId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="netProtocolAppList" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="houseId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="ip" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="port" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="firstTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "idcId",
    "netProtocolAppList"
})
@XmlRootElement(name = "netProtocolApp")
public class NetProtocolApp {

    protected long idcId;
    @XmlElement(required = true)
    protected List<NetProtocolApp.NetProtocolAppList> netProtocolAppList;

    /**
     * Gets the value of the idcId property.
     * 
     */
    public long getIdcId() {
        return idcId;
    }

    /**
     * Sets the value of the idcId property.
     * 
     */
    public void setIdcId(long value) {
        this.idcId = value;
    }

    /**
     * Gets the value of the netProtocolAppList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the netProtocolAppList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNetProtocolAppList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NetProtocolApp.NetProtocolAppList }
     * 
     * 
     */
    public List<NetProtocolApp.NetProtocolAppList> getNetProtocolAppList() {
        if (netProtocolAppList == null) {
            netProtocolAppList = new ArrayList<NetProtocolApp.NetProtocolAppList>();
        }
        return this.netProtocolAppList;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="houseId" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="ip" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="port" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="firstTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "houseId",
        "ip",
        "port",
        "firstTime"
    })
    public static class NetProtocolAppList {

        protected long houseId;
        @XmlElement(required = true)
        protected String ip;
        protected long port;
        @XmlElement(required = true)
        protected String firstTime;

        /**
         * Gets the value of the houseId property.
         * 
         */
        public long getHouseId() {
            return houseId;
        }

        /**
         * Sets the value of the houseId property.
         * 
         */
        public void setHouseId(long value) {
            this.houseId = value;
        }

        /**
         * Gets the value of the ip property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIp() {
            return ip;
        }

        /**
         * Sets the value of the ip property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIp(String value) {
            this.ip = value;
        }

        /**
         * Gets the value of the port property.
         * 
         */
        public long getPort() {
            return port;
        }

        /**
         * Sets the value of the port property.
         * 
         */
        public void setPort(long value) {
            this.port = value;
        }

        /**
         * Gets the value of the firstTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFirstTime() {
            return firstTime;
        }

        /**
         * Sets the value of the firstTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFirstTime(String value) {
            this.firstTime = value;
        }

    }

}
