
package com.aotain.smmsapi.task.client.cxf;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-12-23T11:24:45.371+08:00
 * Generated source version: 3.0.0
 * 
 */
public final class CommandackPortType_CommandackHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://webServiceServer.idcWebService.publicInterface.autoBulid.ncs.com", "commandack");

    private CommandackPortType_CommandackHttpPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Commandack.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Commandack ss = new Commandack(wsdlURL, SERVICE_NAME);
        CommandackPortType port = ss.getCommandackHttpPort();  
        
       /* {
        System.out.println("Invoking discoveryData...");
        java.lang.String _discoveryData_in0 = "";
        java.lang.String _discoveryData_in1 = "";
        java.lang.String _discoveryData__return = port.discoveryData(_discoveryData_in0, _discoveryData_in1);
        System.out.println("discoveryData.result=" + _discoveryData__return);


        }
        {
        System.out.println("Invoking subDomainToday...");
        java.lang.String _subDomainToday__return = port.subDomainToday();
        System.out.println("subDomainToday.result=" + _subDomainToday__return);


        }*/
        {
        System.out.println("Invoking idcCommandack...");
        java.lang.String _idcCommandack_in0 = "";
        java.lang.String _idcCommandack_in1 = "";
        java.lang.String _idcCommandack_in2 = "";
        java.lang.String _idcCommandack_in3 = "";
        java.lang.String _idcCommandack_in4 = "";
        int _idcCommandack_in5 = 0;
        int _idcCommandack_in6 = 0;
        int _idcCommandack_in7 = 0;
        java.lang.String _idcCommandack_in8 = "";
        java.lang.String _idcCommandack__return = port.idcCommandack(_idcCommandack_in0, _idcCommandack_in1, _idcCommandack_in2, _idcCommandack_in3, _idcCommandack_in4, _idcCommandack_in5, _idcCommandack_in6, _idcCommandack_in7, _idcCommandack_in8);
        System.out.println("idcCommandack.result=" + _idcCommandack__return);


        }
        /*{
        System.out.println("Invoking trafficWarning...");
        java.lang.Long _trafficWarning_in0 = null;
        java.lang.Long _trafficWarning_in1 = null;
        java.lang.Long _trafficWarning_in2 = null;
        java.lang.String _trafficWarning_in3 = "";
        java.lang.String _trafficWarning__return = port.trafficWarning(_trafficWarning_in0, _trafficWarning_in1, _trafficWarning_in2, _trafficWarning_in3);
        System.out.println("trafficWarning.result=" + _trafficWarning__return);


        }
        {
        System.out.println("Invoking idcCommandackProvince...");
        java.lang.Long _idcCommandackProvince_in0 = null;
        java.lang.String _idcCommandackProvince_in1 = "";
        java.lang.String _idcCommandackProvince_in2 = "";
        java.lang.String _idcCommandackProvince_in3 = "";
        java.lang.String _idcCommandackProvince_in4 = "";
        int _idcCommandackProvince_in5 = 0;
        int _idcCommandackProvince_in6 = 0;
        int _idcCommandackProvince_in7 = 0;
        java.lang.String _idcCommandackProvince_in8 = "";
        java.lang.String _idcCommandackProvince__return = port.idcCommandackProvince(_idcCommandackProvince_in0, _idcCommandackProvince_in1, _idcCommandackProvince_in2, _idcCommandackProvince_in3, _idcCommandackProvince_in4, _idcCommandackProvince_in5, _idcCommandackProvince_in6, _idcCommandackProvince_in7, _idcCommandackProvince_in8);
        System.out.println("idcCommandackProvince.result=" + _idcCommandackProvince__return);


        }
        {
        System.out.println("Invoking selTopDomain...");
        java.lang.String _selTopDomain__return = port.selTopDomain();
        System.out.println("selTopDomain.result=" + _selTopDomain__return);


        }
        {
        System.out.println("Invoking subDomainLimit...");
        java.lang.Long _subDomainLimit_in0 = null;
        java.lang.Long _subDomainLimit_in1 = null;
        java.lang.String _subDomainLimit__return = port.subDomainLimit(_subDomainLimit_in0, _subDomainLimit_in1);
        System.out.println("subDomainLimit.result=" + _subDomainLimit__return);


        }
        {
        System.out.println("Invoking isolationRelease...");
        java.lang.String _isolationRelease_in0 = "";
        java.lang.String _isolationRelease_in1 = "";
        java.lang.String _isolationRelease_in2 = "";
        java.lang.String _isolationRelease_in3 = "";
        java.lang.String _isolationRelease_in4 = "";
        java.lang.Long _isolationRelease_in5 = null;
        java.lang.Long _isolationRelease_in6 = null;
        java.lang.String _isolationRelease__return = port.isolationRelease(_isolationRelease_in0, _isolationRelease_in1, _isolationRelease_in2, _isolationRelease_in3, _isolationRelease_in4, _isolationRelease_in5, _isolationRelease_in6);
        System.out.println("isolationRelease.result=" + _isolationRelease__return);


        }
        {
        System.out.println("Invoking custom...");
        java.lang.String _custom_in0 = "";
        java.lang.String _custom_in1 = "";
        java.lang.String _custom_in2 = "";
        java.lang.String _custom_in3 = "";
        java.lang.String _custom_in4 = "";
        java.lang.Long _custom_in5 = null;
        java.lang.String _custom__return = port.custom(_custom_in0, _custom_in1, _custom_in2, _custom_in3, _custom_in4, _custom_in5);
        System.out.println("custom.result=" + _custom__return);


        }
        {
        System.out.println("Invoking bigScreen...");
        java.lang.String _bigScreen_in0 = "";
        java.lang.String _bigScreen__return = port.bigScreen(_bigScreen_in0);
        System.out.println("bigScreen.result=" + _bigScreen__return);


        }*/

        System.exit(0);
    }

}
