//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.14 at 02:35:40 下午 CST 
//


package com.aotain.smmsapi.task.bean;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idcId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="filterAmountDataList" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="houseId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="content" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="times" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "idcId",
    "filterAmountDataList"
})
@XmlRootElement(name = "filterAmountData")
public class FilterAmountData {

    protected long idcId;
    @XmlElement(required = true)
    protected List<FilterAmountData.FilterAmountDataList> filterAmountDataList;

    /**
     * Gets the value of the idcId property.
     * 
     */
    public long getIdcId() {
        return idcId;
    }

    /**
     * Sets the value of the idcId property.
     * 
     */
    public void setIdcId(long value) {
        this.idcId = value;
    }

    /**
     * Gets the value of the filterAmountDataList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the filterAmountDataList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFilterAmountDataList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FilterAmountData.FilterAmountDataList }
     * 
     * 
     */
    public List<FilterAmountData.FilterAmountDataList> getFilterAmountDataList() {
        if (filterAmountDataList == null) {
            filterAmountDataList = new ArrayList<FilterAmountData.FilterAmountDataList>();
        }
        return this.filterAmountDataList;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="houseId" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="content" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="times" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "houseId",
        "date",
        "category",
        "content",
        "times"
    })
    public static class FilterAmountDataList {

        protected long houseId;
        @XmlElement(required = true)
        protected String date;
        protected long category;
        @XmlElement(required = true)
        protected String content;
        protected long times;

        /**
         * Gets the value of the houseId property.
         * 
         */
        public long getHouseId() {
            return houseId;
        }

        /**
         * Sets the value of the houseId property.
         * 
         */
        public void setHouseId(long value) {
            this.houseId = value;
        }

        /**
         * Gets the value of the date property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDate(String value) {
            this.date = value;
        }

        /**
         * Gets the value of the category property.
         * 
         */
        public long getCategory() {
            return category;
        }

        /**
         * Sets the value of the category property.
         * 
         */
        public void setCategory(long value) {
            this.category = value;
        }

        /**
         * Gets the value of the content property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContent() {
            return content;
        }

        /**
         * Sets the value of the content property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContent(String value) {
            this.content = value;
        }

        /**
         * Gets the value of the times property.
         * 
         */
        public long getTimes() {
            return times;
        }

        /**
         * Sets the value of the times property.
         * 
         */
        public void setTimes(long value) {
            this.times = value;
        }

    }

}
