//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.14 at 02:35:40 下午 CST 
//


package com.aotain.smmsapi.task.bean;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idcId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="commandId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="command" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="commandId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="rule" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="subtype" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                             &lt;element name="valueStart" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="valueEnd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="keywordRange" type="{http://www.w3.org/2001/XMLSchema}integer" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="action">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="reason" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="log" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                             &lt;element name="report" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="time">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="effectTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="expiredTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="range" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="idcId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="houseId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="privilege">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="owner" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="visible" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="timeStamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "idcId",
    "commandId",
    "amount",
    "command",
    "timeStamp"
})
@XmlRootElement(name = "commandQueryResult")
public class CommandQueryResult {

    @XmlElement(required = true)
    protected String idcId;
    protected long commandId;
    protected long amount;
    @XmlElement(required = true)
    protected List<CommandQueryResult.Command> command;
    @XmlElement(required = true)
    protected String timeStamp;

    /**
     * Gets the value of the idcId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdcId() {
        return idcId;
    }

    /**
     * Sets the value of the idcId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdcId(String value) {
        this.idcId = value;
    }

    /**
     * Gets the value of the commandId property.
     * 
     */
    public long getCommandId() {
        return commandId;
    }

    /**
     * Sets the value of the commandId property.
     * 
     */
    public void setCommandId(long value) {
        this.commandId = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     */
    public long getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     */
    public void setAmount(long value) {
        this.amount = value;
    }

    /**
     * Gets the value of the command property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the command property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCommand().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CommandQueryResult.Command }
     * 
     * 
     */
    public List<CommandQueryResult.Command> getCommand() {
        if (command == null) {
            command = new ArrayList<CommandQueryResult.Command>();
        }
        return this.command;
    }

    /**
     * Gets the value of the timeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeStamp() {
        return timeStamp;
    }

    /**
     * Sets the value of the timeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeStamp(String value) {
        this.timeStamp = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="commandId" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="rule" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="subtype" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                   &lt;element name="valueStart" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="valueEnd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="keywordRange" type="{http://www.w3.org/2001/XMLSchema}integer" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="action">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="reason" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="log" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                   &lt;element name="report" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="time">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="effectTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="expiredTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="range" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="idcId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="houseId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="privilege">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="owner" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="visible" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "commandId",
        "type",
        "rule",
        "action",
        "time",
        "range",
        "privilege"
    })
    public static class Command {

        protected long commandId;
        @XmlElement(required = true)
        protected BigInteger type;
        @XmlElement(required = true)
        protected List<CommandQueryResult.Command.Rule> rule;
        @XmlElement(required = true)
        protected CommandQueryResult.Command.Action action;
        @XmlElement(required = true)
        protected CommandQueryResult.Command.Time time;
        protected CommandQueryResult.Command.Range range;
        @XmlElement(required = true)
        protected CommandQueryResult.Command.Privilege privilege;

        /**
         * Gets the value of the commandId property.
         * 
         */
        public long getCommandId() {
            return commandId;
        }

        /**
         * Sets the value of the commandId property.
         * 
         */
        public void setCommandId(long value) {
            this.commandId = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setType(BigInteger value) {
            this.type = value;
        }

        /**
         * Gets the value of the rule property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the rule property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRule().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CommandQueryResult.Command.Rule }
         * 
         * 
         */
        public List<CommandQueryResult.Command.Rule> getRule() {
            if (rule == null) {
                rule = new ArrayList<CommandQueryResult.Command.Rule>();
            }
            return this.rule;
        }

        /**
         * Gets the value of the action property.
         * 
         * @return
         *     possible object is
         *     {@link CommandQueryResult.Command.Action }
         *     
         */
        public CommandQueryResult.Command.Action getAction() {
            return action;
        }

        /**
         * Sets the value of the action property.
         * 
         * @param value
         *     allowed object is
         *     {@link CommandQueryResult.Command.Action }
         *     
         */
        public void setAction(CommandQueryResult.Command.Action value) {
            this.action = value;
        }

        /**
         * Gets the value of the time property.
         * 
         * @return
         *     possible object is
         *     {@link CommandQueryResult.Command.Time }
         *     
         */
        public CommandQueryResult.Command.Time getTime() {
            return time;
        }

        /**
         * Sets the value of the time property.
         * 
         * @param value
         *     allowed object is
         *     {@link CommandQueryResult.Command.Time }
         *     
         */
        public void setTime(CommandQueryResult.Command.Time value) {
            this.time = value;
        }

        /**
         * Gets the value of the range property.
         * 
         * @return
         *     possible object is
         *     {@link CommandQueryResult.Command.Range }
         *     
         */
        public CommandQueryResult.Command.Range getRange() {
            return range;
        }

        /**
         * Sets the value of the range property.
         * 
         * @param value
         *     allowed object is
         *     {@link CommandQueryResult.Command.Range }
         *     
         */
        public void setRange(CommandQueryResult.Command.Range value) {
            this.range = value;
        }

        /**
         * Gets the value of the privilege property.
         * 
         * @return
         *     possible object is
         *     {@link CommandQueryResult.Command.Privilege }
         *     
         */
        public CommandQueryResult.Command.Privilege getPrivilege() {
            return privilege;
        }

        /**
         * Sets the value of the privilege property.
         * 
         * @param value
         *     allowed object is
         *     {@link CommandQueryResult.Command.Privilege }
         *     
         */
        public void setPrivilege(CommandQueryResult.Command.Privilege value) {
            this.privilege = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="reason" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="log" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="report" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "reason",
            "log",
            "report"
        })
        public static class Action {

            @XmlElement(required = true)
            protected String reason;
            @XmlElement(required = true)
            protected BigInteger log;
            @XmlElement(required = true)
            protected BigInteger report;

            /**
             * Gets the value of the reason property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getReason() {
                return reason;
            }

            /**
             * Sets the value of the reason property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setReason(String value) {
                this.reason = value;
            }

            /**
             * Gets the value of the log property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getLog() {
                return log;
            }

            /**
             * Sets the value of the log property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setLog(BigInteger value) {
                this.log = value;
            }

            /**
             * Gets the value of the report property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getReport() {
                return report;
            }

            /**
             * Sets the value of the report property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setReport(BigInteger value) {
                this.report = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="owner" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="visible" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "owner",
            "visible"
        })
        public static class Privilege {

            @XmlElement(required = true)
            protected String owner;
            @XmlElement(required = true)
            protected BigInteger visible;

            /**
             * Gets the value of the owner property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOwner() {
                return owner;
            }

            /**
             * Sets the value of the owner property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOwner(String value) {
                this.owner = value;
            }

            /**
             * Gets the value of the visible property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getVisible() {
                return visible;
            }

            /**
             * Sets the value of the visible property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setVisible(BigInteger value) {
                this.visible = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="idcId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="houseId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "idcId",
            "houseId"
        })
        public static class Range {

            protected String idcId;
            protected Long houseId;

            /**
             * Gets the value of the idcId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIdcId() {
                return idcId;
            }

            /**
             * Sets the value of the idcId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIdcId(String value) {
                this.idcId = value;
            }

            /**
             * Gets the value of the houseId property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public Long getHouseId() {
                return houseId;
            }

            /**
             * Sets the value of the houseId property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setHouseId(Long value) {
                this.houseId = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="subtype" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="valueStart" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="valueEnd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="keywordRange" type="{http://www.w3.org/2001/XMLSchema}integer" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "subtype",
            "valueStart",
            "valueEnd",
            "keywordRange"
        })
        public static class Rule {

            @XmlElement(required = true)
            protected BigInteger subtype;
            @XmlElement(required = true)
            protected String valueStart;
            protected String valueEnd;
            protected List<BigInteger> keywordRange;

            /**
             * Gets the value of the subtype property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getSubtype() {
                return subtype;
            }

            /**
             * Sets the value of the subtype property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setSubtype(BigInteger value) {
                this.subtype = value;
            }

            /**
             * Gets the value of the valueStart property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValueStart() {
                return valueStart;
            }

            /**
             * Sets the value of the valueStart property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValueStart(String value) {
                this.valueStart = value;
            }

            /**
             * Gets the value of the valueEnd property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValueEnd() {
                return valueEnd;
            }

            /**
             * Sets the value of the valueEnd property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValueEnd(String value) {
                this.valueEnd = value;
            }

            /**
             * Gets the value of the keywordRange property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the keywordRange property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getKeywordRange().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link BigInteger }
             * 
             * 
             */
            public List<BigInteger> getKeywordRange() {
                if (keywordRange == null) {
                    keywordRange = new ArrayList<BigInteger>();
                }
                return this.keywordRange;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="effectTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="expiredTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "effectTime",
            "expiredTime"
        })
        public static class Time {

            @XmlElement(required = true)
            protected String effectTime;
            @XmlElement(required = true)
            protected String expiredTime;

            /**
             * Gets the value of the effectTime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEffectTime() {
                return effectTime;
            }

            /**
             * Sets the value of the effectTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEffectTime(String value) {
                this.effectTime = value;
            }

            /**
             * Gets the value of the expiredTime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getExpiredTime() {
                return expiredTime;
            }

            /**
             * Sets the value of the expiredTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setExpiredTime(String value) {
                this.expiredTime = value;
            }

        }

    }

}
