//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.14 at 02:35:40 下午 CST 
//


package com.aotain.smmsapi.task.bean;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Resource_Monitoring">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Resource_Monitorings">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;choice>
 *                             &lt;element name="FindTopDomainList" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="findTopDomainListTopDomain" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="findTopDomainListFirstTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="findTopDomainListLastTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="findTopDomainListVisitsAmount" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="block" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="record" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="baseUnit_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="flag" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="topDomainMD5" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="machineHouse_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="FindSubDoaminList" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="findSubDoaminListSubDomain" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="findSubDoaminListFirstTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="findSubDoaminListLastTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="findSubDoaminListVisitsAmount" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="block" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="topDomainMD5" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="subDomainMD5" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="baseUnit_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="flag" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="FindIpList" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="findIpListIp" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="findIpListIpStr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="findIpListFirstTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="findIpListLastTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="findIpListVisitsAmount" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="block" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="baseUnit_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="flag" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="recordStatus" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="subDomainCount" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="topDomainCount" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="machineHouse_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="isInIpSeg" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="ProtocolIdentify" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="protocolIdentifyDomain" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="protocolIdentifyGatherTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="protocolIdentifyTimeStamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="protocol_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="baseUnit_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="machineHouse_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="flag" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="ipPortMd5" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="direction" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="serviceIp" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="serviceIpStr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="s_ipPortMd5" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="ipPort_allMd5" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="identifyType" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *                                       &lt;element name="servicePort" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="FindIp_Domain" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="ip" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="domainMd5" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="baseUnit_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="lastTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/choice>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "IDC_Tables")
public class IDCTables {

    @XmlElement(name = "Resource_Monitoring", required = true)
    protected IDCTables.ResourceMonitoring resourceMonitoring;

    /**
     * Gets the value of the resourceMonitoring property.
     * 
     * @return
     *     possible object is
     *     {@link IDCTables.ResourceMonitoring }
     *     
     */
    public IDCTables.ResourceMonitoring getResourceMonitoring() {
        return resourceMonitoring;
    }

    /**
     * Sets the value of the resourceMonitoring property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDCTables.ResourceMonitoring }
     *     
     */
    public void setResourceMonitoring(IDCTables.ResourceMonitoring value) {
        this.resourceMonitoring = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Resource_Monitorings">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice>
     *                   &lt;element name="FindTopDomainList" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="findTopDomainListTopDomain" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="findTopDomainListFirstTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="findTopDomainListLastTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="findTopDomainListVisitsAmount" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="block" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="record" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="baseUnit_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="flag" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="topDomainMD5" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="machineHouse_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="FindSubDoaminList" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="findSubDoaminListSubDomain" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="findSubDoaminListFirstTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="findSubDoaminListLastTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="findSubDoaminListVisitsAmount" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="block" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="topDomainMD5" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="subDomainMD5" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="baseUnit_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="flag" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="FindIpList" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="findIpListIp" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="findIpListIpStr" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="findIpListFirstTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="findIpListLastTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="findIpListVisitsAmount" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="block" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="baseUnit_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="flag" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="recordStatus" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="subDomainCount" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="topDomainCount" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="machineHouse_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="isInIpSeg" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="ProtocolIdentify" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="protocolIdentifyDomain" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="protocolIdentifyGatherTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="protocolIdentifyTimeStamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="protocol_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="baseUnit_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="machineHouse_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="flag" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="ipPortMd5" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="direction" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="serviceIp" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="serviceIpStr" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="s_ipPortMd5" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="ipPort_allMd5" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="identifyType" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
     *                             &lt;element name="servicePort" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="FindIp_Domain" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="ip" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="domainMd5" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="baseUnit_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="lastTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/choice>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "resourceMonitorings"
    })
    public static class ResourceMonitoring {

        @XmlElement(name = "Resource_Monitorings", required = true)
        protected IDCTables.ResourceMonitoring.ResourceMonitorings resourceMonitorings;

        /**
         * Gets the value of the resourceMonitorings property.
         * 
         * @return
         *     possible object is
         *     {@link IDCTables.ResourceMonitoring.ResourceMonitorings }
         *     
         */
        public IDCTables.ResourceMonitoring.ResourceMonitorings getResourceMonitorings() {
            return resourceMonitorings;
        }

        /**
         * Sets the value of the resourceMonitorings property.
         * 
         * @param value
         *     allowed object is
         *     {@link IDCTables.ResourceMonitoring.ResourceMonitorings }
         *     
         */
        public void setResourceMonitorings(IDCTables.ResourceMonitoring.ResourceMonitorings value) {
            this.resourceMonitorings = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice>
         *         &lt;element name="FindTopDomainList" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="findTopDomainListTopDomain" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="findTopDomainListFirstTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="findTopDomainListLastTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="findTopDomainListVisitsAmount" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="block" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="record" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="baseUnit_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="flag" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="topDomainMD5" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="machineHouse_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="FindSubDoaminList" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="findSubDoaminListSubDomain" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="findSubDoaminListFirstTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="findSubDoaminListLastTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="findSubDoaminListVisitsAmount" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="block" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="topDomainMD5" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="subDomainMD5" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="baseUnit_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="flag" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="FindIpList" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="findIpListIp" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="findIpListIpStr" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="findIpListFirstTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="findIpListLastTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="findIpListVisitsAmount" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="block" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="baseUnit_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="flag" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="recordStatus" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="subDomainCount" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="topDomainCount" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="machineHouse_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="isInIpSeg" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="ProtocolIdentify" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="protocolIdentifyDomain" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="protocolIdentifyGatherTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="protocolIdentifyTimeStamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="protocol_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="baseUnit_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="machineHouse_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="flag" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="ipPortMd5" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="direction" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="serviceIp" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="serviceIpStr" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="s_ipPortMd5" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="ipPort_allMd5" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="identifyType" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
         *                   &lt;element name="servicePort" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="FindIp_Domain" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="ip" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="domainMd5" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="baseUnit_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="lastTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "findTopDomainList",
            "findSubDoaminList",
            "findIpList",
            "protocolIdentify",
            "findIpDomain"
        })
        public static class ResourceMonitorings {

            @XmlElement(name = "FindTopDomainList")
            protected List<IDCTables.ResourceMonitoring.ResourceMonitorings.FindTopDomainList> findTopDomainList;
            @XmlElement(name = "FindSubDoaminList")
            protected List<IDCTables.ResourceMonitoring.ResourceMonitorings.FindSubDoaminList> findSubDoaminList;
            @XmlElement(name = "FindIpList")
            protected List<IDCTables.ResourceMonitoring.ResourceMonitorings.FindIpList> findIpList;
            @XmlElement(name = "ProtocolIdentify")
            protected List<IDCTables.ResourceMonitoring.ResourceMonitorings.ProtocolIdentify> protocolIdentify;
            @XmlElement(name = "FindIp_Domain")
            protected List<IDCTables.ResourceMonitoring.ResourceMonitorings.FindIpDomain> findIpDomain;

            /**
             * Gets the value of the findTopDomainList property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the findTopDomainList property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getFindTopDomainList().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link IDCTables.ResourceMonitoring.ResourceMonitorings.FindTopDomainList }
             * 
             * 
             */
            public List<IDCTables.ResourceMonitoring.ResourceMonitorings.FindTopDomainList> getFindTopDomainList() {
                if (findTopDomainList == null) {
                    findTopDomainList = new ArrayList<IDCTables.ResourceMonitoring.ResourceMonitorings.FindTopDomainList>();
                }
                return this.findTopDomainList;
            }

            /**
             * Gets the value of the findSubDoaminList property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the findSubDoaminList property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getFindSubDoaminList().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link IDCTables.ResourceMonitoring.ResourceMonitorings.FindSubDoaminList }
             * 
             * 
             */
            public List<IDCTables.ResourceMonitoring.ResourceMonitorings.FindSubDoaminList> getFindSubDoaminList() {
                if (findSubDoaminList == null) {
                    findSubDoaminList = new ArrayList<IDCTables.ResourceMonitoring.ResourceMonitorings.FindSubDoaminList>();
                }
                return this.findSubDoaminList;
            }

            /**
             * Gets the value of the findIpList property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the findIpList property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getFindIpList().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link IDCTables.ResourceMonitoring.ResourceMonitorings.FindIpList }
             * 
             * 
             */
            public List<IDCTables.ResourceMonitoring.ResourceMonitorings.FindIpList> getFindIpList() {
                if (findIpList == null) {
                    findIpList = new ArrayList<IDCTables.ResourceMonitoring.ResourceMonitorings.FindIpList>();
                }
                return this.findIpList;
            }

            /**
             * Gets the value of the protocolIdentify property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the protocolIdentify property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getProtocolIdentify().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link IDCTables.ResourceMonitoring.ResourceMonitorings.ProtocolIdentify }
             * 
             * 
             */
            public List<IDCTables.ResourceMonitoring.ResourceMonitorings.ProtocolIdentify> getProtocolIdentify() {
                if (protocolIdentify == null) {
                    protocolIdentify = new ArrayList<IDCTables.ResourceMonitoring.ResourceMonitorings.ProtocolIdentify>();
                }
                return this.protocolIdentify;
            }

            /**
             * Gets the value of the findIpDomain property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the findIpDomain property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getFindIpDomain().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link IDCTables.ResourceMonitoring.ResourceMonitorings.FindIpDomain }
             * 
             * 
             */
            public List<IDCTables.ResourceMonitoring.ResourceMonitorings.FindIpDomain> getFindIpDomain() {
                if (findIpDomain == null) {
                    findIpDomain = new ArrayList<IDCTables.ResourceMonitoring.ResourceMonitorings.FindIpDomain>();
                }
                return this.findIpDomain;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="ip" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="domainMd5" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="baseUnit_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="lastTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "ip",
                "domainMd5",
                "type",
                "baseUnitId",
                "lastTime"
            })
            public static class FindIpDomain {

                protected long ip;
                @XmlElement(required = true)
                protected String domainMd5;
                protected long type;
                @XmlElement(name = "baseUnit_id")
                protected long baseUnitId;
                @XmlElement(required = true)
                protected String lastTime;

                /**
                 * Gets the value of the ip property.
                 * 
                 */
                public long getIp() {
                    return ip;
                }

                /**
                 * Sets the value of the ip property.
                 * 
                 */
                public void setIp(long value) {
                    this.ip = value;
                }

                /**
                 * Gets the value of the domainMd5 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDomainMd5() {
                    return domainMd5;
                }

                /**
                 * Sets the value of the domainMd5 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDomainMd5(String value) {
                    this.domainMd5 = value;
                }

                /**
                 * Gets the value of the type property.
                 * 
                 */
                public long getType() {
                    return type;
                }

                /**
                 * Sets the value of the type property.
                 * 
                 */
                public void setType(long value) {
                    this.type = value;
                }

                /**
                 * Gets the value of the baseUnitId property.
                 * 
                 */
                public long getBaseUnitId() {
                    return baseUnitId;
                }

                /**
                 * Sets the value of the baseUnitId property.
                 * 
                 */
                public void setBaseUnitId(long value) {
                    this.baseUnitId = value;
                }

                /**
                 * Gets the value of the lastTime property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLastTime() {
                    return lastTime;
                }

                /**
                 * Sets the value of the lastTime property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLastTime(String value) {
                    this.lastTime = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="findIpListIp" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="findIpListIpStr" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="findIpListFirstTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="findIpListLastTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="findIpListVisitsAmount" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="block" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="baseUnit_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="flag" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="recordStatus" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="subDomainCount" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="topDomainCount" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="machineHouse_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="isInIpSeg" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "findIpListIp",
                "findIpListIpStr",
                "findIpListFirstTime",
                "findIpListLastTime",
                "findIpListVisitsAmount",
                "block",
                "baseUnitId",
                "flag",
                "recordStatus",
                "subDomainCount",
                "topDomainCount",
                "machineHouseId",
                "isInIpSeg"
            })
            public static class FindIpList {

                protected long findIpListIp;
                @XmlElement(required = true)
                protected String findIpListIpStr;
                @XmlElement(required = true)
                protected String findIpListFirstTime;
                @XmlElement(required = true)
                protected String findIpListLastTime;
                protected long findIpListVisitsAmount;
                protected long block;
                @XmlElement(name = "baseUnit_id")
                protected long baseUnitId;
                protected long flag;
                protected long recordStatus;
                protected long subDomainCount;
                protected long topDomainCount;
                @XmlElement(name = "machineHouse_id")
                protected long machineHouseId;
                protected long isInIpSeg;

                /**
                 * Gets the value of the findIpListIp property.
                 * 
                 */
                public long getFindIpListIp() {
                    return findIpListIp;
                }

                /**
                 * Sets the value of the findIpListIp property.
                 * 
                 */
                public void setFindIpListIp(long value) {
                    this.findIpListIp = value;
                }

                /**
                 * Gets the value of the findIpListIpStr property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFindIpListIpStr() {
                    return findIpListIpStr;
                }

                /**
                 * Sets the value of the findIpListIpStr property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFindIpListIpStr(String value) {
                    this.findIpListIpStr = value;
                }

                /**
                 * Gets the value of the findIpListFirstTime property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFindIpListFirstTime() {
                    return findIpListFirstTime;
                }

                /**
                 * Sets the value of the findIpListFirstTime property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFindIpListFirstTime(String value) {
                    this.findIpListFirstTime = value;
                }

                /**
                 * Gets the value of the findIpListLastTime property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFindIpListLastTime() {
                    return findIpListLastTime;
                }

                /**
                 * Sets the value of the findIpListLastTime property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFindIpListLastTime(String value) {
                    this.findIpListLastTime = value;
                }

                /**
                 * Gets the value of the findIpListVisitsAmount property.
                 * 
                 */
                public long getFindIpListVisitsAmount() {
                    return findIpListVisitsAmount;
                }

                /**
                 * Sets the value of the findIpListVisitsAmount property.
                 * 
                 */
                public void setFindIpListVisitsAmount(long value) {
                    this.findIpListVisitsAmount = value;
                }

                /**
                 * Gets the value of the block property.
                 * 
                 */
                public long getBlock() {
                    return block;
                }

                /**
                 * Sets the value of the block property.
                 * 
                 */
                public void setBlock(long value) {
                    this.block = value;
                }

                /**
                 * Gets the value of the baseUnitId property.
                 * 
                 */
                public long getBaseUnitId() {
                    return baseUnitId;
                }

                /**
                 * Sets the value of the baseUnitId property.
                 * 
                 */
                public void setBaseUnitId(long value) {
                    this.baseUnitId = value;
                }

                /**
                 * Gets the value of the flag property.
                 * 
                 */
                public long getFlag() {
                    return flag;
                }

                /**
                 * Sets the value of the flag property.
                 * 
                 */
                public void setFlag(long value) {
                    this.flag = value;
                }

                /**
                 * Gets the value of the recordStatus property.
                 * 
                 */
                public long getRecordStatus() {
                    return recordStatus;
                }

                /**
                 * Sets the value of the recordStatus property.
                 * 
                 */
                public void setRecordStatus(long value) {
                    this.recordStatus = value;
                }

                /**
                 * Gets the value of the subDomainCount property.
                 * 
                 */
                public long getSubDomainCount() {
                    return subDomainCount;
                }

                /**
                 * Sets the value of the subDomainCount property.
                 * 
                 */
                public void setSubDomainCount(long value) {
                    this.subDomainCount = value;
                }

                /**
                 * Gets the value of the topDomainCount property.
                 * 
                 */
                public long getTopDomainCount() {
                    return topDomainCount;
                }

                /**
                 * Sets the value of the topDomainCount property.
                 * 
                 */
                public void setTopDomainCount(long value) {
                    this.topDomainCount = value;
                }

                /**
                 * Gets the value of the machineHouseId property.
                 * 
                 */
                public long getMachineHouseId() {
                    return machineHouseId;
                }

                /**
                 * Sets the value of the machineHouseId property.
                 * 
                 */
                public void setMachineHouseId(long value) {
                    this.machineHouseId = value;
                }

                /**
                 * Gets the value of the isInIpSeg property.
                 * 
                 */
                public long getIsInIpSeg() {
                    return isInIpSeg;
                }

                /**
                 * Sets the value of the isInIpSeg property.
                 * 
                 */
                public void setIsInIpSeg(long value) {
                    this.isInIpSeg = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="findSubDoaminListSubDomain" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="findSubDoaminListFirstTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="findSubDoaminListLastTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="findSubDoaminListVisitsAmount" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="block" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="topDomainMD5" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="subDomainMD5" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="baseUnit_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="flag" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "findSubDoaminListSubDomain",
                "findSubDoaminListFirstTime",
                "findSubDoaminListLastTime",
                "findSubDoaminListVisitsAmount",
                "block",
                "topDomainMD5",
                "subDomainMD5",
                "baseUnitId",
                "flag"
            })
            public static class FindSubDoaminList {

                @XmlElement(required = true)
                protected String findSubDoaminListSubDomain;
                @XmlElement(required = true)
                protected String findSubDoaminListFirstTime;
                @XmlElement(required = true)
                protected String findSubDoaminListLastTime;
                protected long findSubDoaminListVisitsAmount;
                protected long block;
                @XmlElement(required = true)
                protected String topDomainMD5;
                @XmlElement(required = true)
                protected String subDomainMD5;
                @XmlElement(name = "baseUnit_id")
                protected long baseUnitId;
                protected long flag;

                /**
                 * Gets the value of the findSubDoaminListSubDomain property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFindSubDoaminListSubDomain() {
                    return findSubDoaminListSubDomain;
                }

                /**
                 * Sets the value of the findSubDoaminListSubDomain property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFindSubDoaminListSubDomain(String value) {
                    this.findSubDoaminListSubDomain = value;
                }

                /**
                 * Gets the value of the findSubDoaminListFirstTime property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFindSubDoaminListFirstTime() {
                    return findSubDoaminListFirstTime;
                }

                /**
                 * Sets the value of the findSubDoaminListFirstTime property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFindSubDoaminListFirstTime(String value) {
                    this.findSubDoaminListFirstTime = value;
                }

                /**
                 * Gets the value of the findSubDoaminListLastTime property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFindSubDoaminListLastTime() {
                    return findSubDoaminListLastTime;
                }

                /**
                 * Sets the value of the findSubDoaminListLastTime property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFindSubDoaminListLastTime(String value) {
                    this.findSubDoaminListLastTime = value;
                }

                /**
                 * Gets the value of the findSubDoaminListVisitsAmount property.
                 * 
                 */
                public long getFindSubDoaminListVisitsAmount() {
                    return findSubDoaminListVisitsAmount;
                }

                /**
                 * Sets the value of the findSubDoaminListVisitsAmount property.
                 * 
                 */
                public void setFindSubDoaminListVisitsAmount(long value) {
                    this.findSubDoaminListVisitsAmount = value;
                }

                /**
                 * Gets the value of the block property.
                 * 
                 */
                public long getBlock() {
                    return block;
                }

                /**
                 * Sets the value of the block property.
                 * 
                 */
                public void setBlock(long value) {
                    this.block = value;
                }

                /**
                 * Gets the value of the topDomainMD5 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTopDomainMD5() {
                    return topDomainMD5;
                }

                /**
                 * Sets the value of the topDomainMD5 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTopDomainMD5(String value) {
                    this.topDomainMD5 = value;
                }

                /**
                 * Gets the value of the subDomainMD5 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSubDomainMD5() {
                    return subDomainMD5;
                }

                /**
                 * Sets the value of the subDomainMD5 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSubDomainMD5(String value) {
                    this.subDomainMD5 = value;
                }

                /**
                 * Gets the value of the baseUnitId property.
                 * 
                 */
                public long getBaseUnitId() {
                    return baseUnitId;
                }

                /**
                 * Sets the value of the baseUnitId property.
                 * 
                 */
                public void setBaseUnitId(long value) {
                    this.baseUnitId = value;
                }

                /**
                 * Gets the value of the flag property.
                 * 
                 */
                public long getFlag() {
                    return flag;
                }

                /**
                 * Sets the value of the flag property.
                 * 
                 */
                public void setFlag(long value) {
                    this.flag = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="findTopDomainListTopDomain" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="findTopDomainListFirstTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="findTopDomainListLastTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="findTopDomainListVisitsAmount" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="block" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="record" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="baseUnit_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="flag" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="topDomainMD5" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="machineHouse_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "findTopDomainListTopDomain",
                "findTopDomainListFirstTime",
                "findTopDomainListLastTime",
                "findTopDomainListVisitsAmount",
                "block",
                "record",
                "type",
                "baseUnitId",
                "flag",
                "topDomainMD5",
                "machineHouseId"
            })
            public static class FindTopDomainList {

                @XmlElement(required = true)
                protected String findTopDomainListTopDomain;
                @XmlElement(required = true)
                protected String findTopDomainListFirstTime;
                @XmlElement(required = true)
                protected String findTopDomainListLastTime;
                protected long findTopDomainListVisitsAmount;
                protected long block;
                protected long record;
                protected long type;
                @XmlElement(name = "baseUnit_id")
                protected long baseUnitId;
                protected long flag;
                @XmlElement(required = true)
                protected String topDomainMD5;
                @XmlElement(name = "machineHouse_id")
                protected long machineHouseId;

                /**
                 * Gets the value of the findTopDomainListTopDomain property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFindTopDomainListTopDomain() {
                    return findTopDomainListTopDomain;
                }

                /**
                 * Sets the value of the findTopDomainListTopDomain property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFindTopDomainListTopDomain(String value) {
                    this.findTopDomainListTopDomain = value;
                }

                /**
                 * Gets the value of the findTopDomainListFirstTime property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFindTopDomainListFirstTime() {
                    return findTopDomainListFirstTime;
                }

                /**
                 * Sets the value of the findTopDomainListFirstTime property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFindTopDomainListFirstTime(String value) {
                    this.findTopDomainListFirstTime = value;
                }

                /**
                 * Gets the value of the findTopDomainListLastTime property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFindTopDomainListLastTime() {
                    return findTopDomainListLastTime;
                }

                /**
                 * Sets the value of the findTopDomainListLastTime property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFindTopDomainListLastTime(String value) {
                    this.findTopDomainListLastTime = value;
                }

                /**
                 * Gets the value of the findTopDomainListVisitsAmount property.
                 * 
                 */
                public long getFindTopDomainListVisitsAmount() {
                    return findTopDomainListVisitsAmount;
                }

                /**
                 * Sets the value of the findTopDomainListVisitsAmount property.
                 * 
                 */
                public void setFindTopDomainListVisitsAmount(long value) {
                    this.findTopDomainListVisitsAmount = value;
                }

                /**
                 * Gets the value of the block property.
                 * 
                 */
                public long getBlock() {
                    return block;
                }

                /**
                 * Sets the value of the block property.
                 * 
                 */
                public void setBlock(long value) {
                    this.block = value;
                }

                /**
                 * Gets the value of the record property.
                 * 
                 */
                public long getRecord() {
                    return record;
                }

                /**
                 * Sets the value of the record property.
                 * 
                 */
                public void setRecord(long value) {
                    this.record = value;
                }

                /**
                 * Gets the value of the type property.
                 * 
                 */
                public long getType() {
                    return type;
                }

                /**
                 * Sets the value of the type property.
                 * 
                 */
                public void setType(long value) {
                    this.type = value;
                }

                /**
                 * Gets the value of the baseUnitId property.
                 * 
                 */
                public long getBaseUnitId() {
                    return baseUnitId;
                }

                /**
                 * Sets the value of the baseUnitId property.
                 * 
                 */
                public void setBaseUnitId(long value) {
                    this.baseUnitId = value;
                }

                /**
                 * Gets the value of the flag property.
                 * 
                 */
                public long getFlag() {
                    return flag;
                }

                /**
                 * Sets the value of the flag property.
                 * 
                 */
                public void setFlag(long value) {
                    this.flag = value;
                }

                /**
                 * Gets the value of the topDomainMD5 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTopDomainMD5() {
                    return topDomainMD5;
                }

                /**
                 * Sets the value of the topDomainMD5 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTopDomainMD5(String value) {
                    this.topDomainMD5 = value;
                }

                /**
                 * Gets the value of the machineHouseId property.
                 * 
                 */
                public long getMachineHouseId() {
                    return machineHouseId;
                }

                /**
                 * Sets the value of the machineHouseId property.
                 * 
                 */
                public void setMachineHouseId(long value) {
                    this.machineHouseId = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="protocolIdentifyDomain" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="protocolIdentifyGatherTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="protocolIdentifyTimeStamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="protocol_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="baseUnit_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="machineHouse_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="flag" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="ipPortMd5" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="direction" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="serviceIp" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="serviceIpStr" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="s_ipPortMd5" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="ipPort_allMd5" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="identifyType" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
             *         &lt;element name="servicePort" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "protocolIdentifyDomain",
                "protocolIdentifyGatherTime",
                "protocolIdentifyTimeStamp",
                "protocolId",
                "baseUnitId",
                "machineHouseId",
                "flag",
                "ipPortMd5",
                "direction",
                "serviceIp",
                "serviceIpStr",
                "sIpPortMd5",
                "ipPortAllMd5",
                "identifyType",
                "servicePort"
            })
            public static class ProtocolIdentify {

                protected String protocolIdentifyDomain;
                @XmlElement(required = true)
                protected String protocolIdentifyGatherTime;
                @XmlElement(required = true)
                protected String protocolIdentifyTimeStamp;
                @XmlElement(name = "protocol_id")
                protected long protocolId;
                @XmlElement(name = "baseUnit_id")
                protected long baseUnitId;
                @XmlElement(name = "machineHouse_id")
                protected long machineHouseId;
                protected long flag;
                @XmlElement(required = true)
                protected String ipPortMd5;
                protected long direction;
                protected long serviceIp;
                @XmlElement(required = true)
                protected String serviceIpStr;
                @XmlElement(name = "s_ipPortMd5", required = true)
                protected String sIpPortMd5;
                @XmlElement(name = "ipPort_allMd5", required = true)
                protected String ipPortAllMd5;
                protected Long identifyType;
                protected long servicePort;

                /**
                 * Gets the value of the protocolIdentifyDomain property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getProtocolIdentifyDomain() {
                    return protocolIdentifyDomain;
                }

                /**
                 * Sets the value of the protocolIdentifyDomain property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setProtocolIdentifyDomain(String value) {
                    this.protocolIdentifyDomain = value;
                }

                /**
                 * Gets the value of the protocolIdentifyGatherTime property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getProtocolIdentifyGatherTime() {
                    return protocolIdentifyGatherTime;
                }

                /**
                 * Sets the value of the protocolIdentifyGatherTime property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setProtocolIdentifyGatherTime(String value) {
                    this.protocolIdentifyGatherTime = value;
                }

                /**
                 * Gets the value of the protocolIdentifyTimeStamp property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getProtocolIdentifyTimeStamp() {
                    return protocolIdentifyTimeStamp;
                }

                /**
                 * Sets the value of the protocolIdentifyTimeStamp property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setProtocolIdentifyTimeStamp(String value) {
                    this.protocolIdentifyTimeStamp = value;
                }

                /**
                 * Gets the value of the protocolId property.
                 * 
                 */
                public long getProtocolId() {
                    return protocolId;
                }

                /**
                 * Sets the value of the protocolId property.
                 * 
                 */
                public void setProtocolId(long value) {
                    this.protocolId = value;
                }

                /**
                 * Gets the value of the baseUnitId property.
                 * 
                 */
                public long getBaseUnitId() {
                    return baseUnitId;
                }

                /**
                 * Sets the value of the baseUnitId property.
                 * 
                 */
                public void setBaseUnitId(long value) {
                    this.baseUnitId = value;
                }

                /**
                 * Gets the value of the machineHouseId property.
                 * 
                 */
                public long getMachineHouseId() {
                    return machineHouseId;
                }

                /**
                 * Sets the value of the machineHouseId property.
                 * 
                 */
                public void setMachineHouseId(long value) {
                    this.machineHouseId = value;
                }

                /**
                 * Gets the value of the flag property.
                 * 
                 */
                public long getFlag() {
                    return flag;
                }

                /**
                 * Sets the value of the flag property.
                 * 
                 */
                public void setFlag(long value) {
                    this.flag = value;
                }

                /**
                 * Gets the value of the ipPortMd5 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getIpPortMd5() {
                    return ipPortMd5;
                }

                /**
                 * Sets the value of the ipPortMd5 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setIpPortMd5(String value) {
                    this.ipPortMd5 = value;
                }

                /**
                 * Gets the value of the direction property.
                 * 
                 */
                public long getDirection() {
                    return direction;
                }

                /**
                 * Sets the value of the direction property.
                 * 
                 */
                public void setDirection(long value) {
                    this.direction = value;
                }

                /**
                 * Gets the value of the serviceIp property.
                 * 
                 */
                public long getServiceIp() {
                    return serviceIp;
                }

                /**
                 * Sets the value of the serviceIp property.
                 * 
                 */
                public void setServiceIp(long value) {
                    this.serviceIp = value;
                }

                /**
                 * Gets the value of the serviceIpStr property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getServiceIpStr() {
                    return serviceIpStr;
                }

                /**
                 * Sets the value of the serviceIpStr property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setServiceIpStr(String value) {
                    this.serviceIpStr = value;
                }

                /**
                 * Gets the value of the sIpPortMd5 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSIpPortMd5() {
                    return sIpPortMd5;
                }

                /**
                 * Sets the value of the sIpPortMd5 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSIpPortMd5(String value) {
                    this.sIpPortMd5 = value;
                }

                /**
                 * Gets the value of the ipPortAllMd5 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getIpPortAllMd5() {
                    return ipPortAllMd5;
                }

                /**
                 * Sets the value of the ipPortAllMd5 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setIpPortAllMd5(String value) {
                    this.ipPortAllMd5 = value;
                }

                /**
                 * Gets the value of the identifyType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Long }
                 *     
                 */
                public Long getIdentifyType() {
                    return identifyType;
                }

                /**
                 * Sets the value of the identifyType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Long }
                 *     
                 */
                public void setIdentifyType(Long value) {
                    this.identifyType = value;
                }

                /**
                 * Gets the value of the servicePort property.
                 * 
                 */
                public long getServicePort() {
                    return servicePort;
                }

                /**
                 * Sets the value of the servicePort property.
                 * 
                 */
                public void setServicePort(long value) {
                    this.servicePort = value;
                }

            }

        }

    }

}
