
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.aotain.smmsapi.task.client.cxf.tj;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2015-12-29T12:41:40.951+08:00
 * Generated source version: 2.7.12
 * 
 */

@javax.jws.WebService(
                      serviceName = "commandack",
                      portName = "commandackHttpPort",
                      targetNamespace = "http://company.service.webservice.smms.ncs.com",
                      wsdlLocation = "http://60.29.111.230:8002/IDCWebService_smms/commandack?wsdl",
                      endpointInterface = "com.aotain.smmsapi.task.client.cxf.tj.CommandackPortType")
                      
public class CommandackPortTypeImpl implements CommandackPortType {

    private static final Logger LOG = Logger.getLogger(CommandackPortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see com.aotain.smmsapi.task.client.cxf.tj.CommandackPortType#idcCommandack(java.lang.String  in0 ,)java.lang.String  in1 ,)java.lang.String  in2 ,)java.lang.String  in3 ,)java.lang.String  in4 ,)java.lang.Integer  in5 ,)java.lang.Integer  in6 ,)java.lang.Integer  in7 ,)java.lang.String  in8 )*
     */
    public java.lang.String idcCommandack(java.lang.String in0,java.lang.String in1,java.lang.String in2,java.lang.String in3,java.lang.String in4,java.lang.Integer in5,java.lang.Integer in6,java.lang.Integer in7,java.lang.String in8) { 
        LOG.info("Executing operation idcCommandack");
        System.out.println(in0);
        System.out.println(in1);
        System.out.println(in2);
        System.out.println(in3);
        System.out.println(in4);
        System.out.println(in5);
        System.out.println(in6);
        System.out.println(in7);
        System.out.println(in8);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
