package com.aotain.smmsapi.task.client.cxf.tj;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2015-12-29T12:41:40.959+08:00
 * Generated source version: 2.7.12
 * 
 */
@WebService(targetNamespace = "http://company.service.webservice.smms.ncs.com", name = "commandackPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface CommandackPortType {

    @WebResult(name = "out", targetNamespace = "http://company.service.webservice.smms.ncs.com")
    @RequestWrapper(localName = "idc_commandack", targetNamespace = "http://company.service.webservice.smms.ncs.com", className = "com.aotain.smmsapi.task.client.cxf.tj.IdcCommandack")
    @WebMethod(operationName = "idc_commandack")
    @ResponseWrapper(localName = "idc_commandackResponse", targetNamespace = "http://company.service.webservice.smms.ncs.com", className = "com.aotain.smmsapi.task.client.cxf.tj.IdcCommandackResponse")
    public java.lang.String idcCommandack(
        @WebParam(name = "in0", targetNamespace = "http://company.service.webservice.smms.ncs.com")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://company.service.webservice.smms.ncs.com")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://company.service.webservice.smms.ncs.com")
        java.lang.String in2,
        @WebParam(name = "in3", targetNamespace = "http://company.service.webservice.smms.ncs.com")
        java.lang.String in3,
        @WebParam(name = "in4", targetNamespace = "http://company.service.webservice.smms.ncs.com")
        java.lang.String in4,
        @WebParam(name = "in5", targetNamespace = "http://company.service.webservice.smms.ncs.com")
        java.lang.Integer in5,
        @WebParam(name = "in6", targetNamespace = "http://company.service.webservice.smms.ncs.com")
        java.lang.Integer in6,
        @WebParam(name = "in7", targetNamespace = "http://company.service.webservice.smms.ncs.com")
        java.lang.Integer in7,
        @WebParam(name = "in8", targetNamespace = "http://company.service.webservice.smms.ncs.com")
        java.lang.String in8
    );
}
