
package com.aotain.smmsapi.task.client.cxf1;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2015-07-14T11:09:19.549+08:00
 * Generated source version: 2.7.12
 * 
 */
public final class IdcWebService_IdcWebServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice.ismi.surfilter.com/", "IDCWebService");

    private IdcWebService_IdcWebServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = IDCWebService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        IDCWebService_Service ss = new IDCWebService_Service(wsdlURL, SERVICE_NAME);
        IdcWebService port = ss.getIdcWebServicePort();  
        
        {
        System.out.println("Invoking idcCommandack...");
        java.lang.String _idcCommandack_idcId = "";
        java.lang.String _idcCommandack_randVal = "";
        java.lang.String _idcCommandack_pwdHash = "";
        java.lang.String _idcCommandack_result = "";
        java.lang.String _idcCommandack_resultHash = "";
        int _idcCommandack_encryptAlgorithm = 0;
        int _idcCommandack_hashAlgorithm = 0;
        int _idcCommandack_compressionFormat = 0;
        java.lang.String _idcCommandack_commandVersion = "";
        java.lang.String _idcCommandack__return = port.idcCommandack(_idcCommandack_idcId, _idcCommandack_randVal, _idcCommandack_pwdHash, _idcCommandack_result, _idcCommandack_resultHash, _idcCommandack_encryptAlgorithm, _idcCommandack_hashAlgorithm, _idcCommandack_compressionFormat, _idcCommandack_commandVersion);
        System.out.println("idcCommandack.result=" + _idcCommandack__return);


        }

        System.exit(0);
    }

}
