
package com.aotain.smmsapi.task.client.cxf;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-12-23T11:24:45.465+08:00
 * Generated source version: 3.0.0
 * 
 */
 
public class CommandackPortType_CommandackHttpPort_Server{

    protected CommandackPortType_CommandackHttpPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new commandackHttpPortImpl();
        String address = "http://60.29.111.230:7777/DataCenter_New/IDCWebService/commandack";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new CommandackPortType_CommandackHttpPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
