//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.14 at 02:35:40 下午 CST 
//


package com.aotain.smmsapi.task.bean;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.aotain.smmsapi.task.bean package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.aotain.smmsapi.task.bean
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IdcInfoManage }
     * 
     */
    public IdcInfoManage createIdcInfoManage() {
        return new IdcInfoManage();
    }

    /**
     * Create an instance of {@link BasicInfo.QueryResult.UserInfo.Info.ServiceInfo.HousesHoldInfo.IpTrans }
     * 
     */
    public BasicInfo.QueryResult.UserInfo.Info.ServiceInfo.HousesHoldInfo.IpTrans createBasicInfoQueryResultUserInfoInfoServiceInfoHousesHoldInfoIpTrans() {
        return new BasicInfo.QueryResult.UserInfo.Info.ServiceInfo.HousesHoldInfo.IpTrans();
    }

    /**
     * Create an instance of {@link BasicInfo.UpdateInfo.UpdateData.UserInfo.Info.ServiceInfo.Domain }
     * 
     */
    public BasicInfo.UpdateInfo.UpdateData.UserInfo.Info.ServiceInfo.Domain createBasicInfoUpdateInfoUpdateDataUserInfoInfoServiceInfoDomain() {
        return new BasicInfo.UpdateInfo.UpdateData.UserInfo.Info.ServiceInfo.Domain();
    }

    /**
     * Create an instance of {@link FilterResult.Log }
     * 
     */
    public FilterResult.Log createFilterResultLog() {
        return new FilterResult.Log();
    }

    /**
     * Create an instance of {@link CodeList.Fwnr }
     * 
     */
    public CodeList.Fwnr createCodeListFwnr() {
        return new CodeList.Fwnr();
    }

    /**
     * Create an instance of {@link CodeList }
     * 
     */
    public CodeList createCodeList() {
        return new CodeList();
    }

    /**
     * Create an instance of {@link IDCTables }
     * 
     */
    public IDCTables createIDCTables() {
        return new IDCTables();
    }

    /**
     * Create an instance of {@link BasicInfo.QueryResult.UserInfo.Info.ServiceInfo.HousesHoldInfo.IpTrans.NetIp }
     * 
     */
    public BasicInfo.QueryResult.UserInfo.Info.ServiceInfo.HousesHoldInfo.IpTrans.NetIp createBasicInfoQueryResultUserInfoInfoServiceInfoHousesHoldInfoIpTransNetIp() {
        return new BasicInfo.QueryResult.UserInfo.Info.ServiceInfo.HousesHoldInfo.IpTrans.NetIp();
    }

    /**
     * Create an instance of {@link BasicInfo.UpdateInfo }
     * 
     */
    public BasicInfo.UpdateInfo createBasicInfoUpdateInfo() {
        return new BasicInfo.UpdateInfo();
    }

    /**
     * Create an instance of {@link BasicInfo.QueryResult.UserInfo.Info }
     * 
     */
    public BasicInfo.QueryResult.UserInfo.Info createBasicInfoQueryResultUserInfoInfo() {
        return new BasicInfo.QueryResult.UserInfo.Info();
    }

    /**
     * Create an instance of {@link ActiveResources.FindIpList }
     * 
     */
    public ActiveResources.FindIpList createActiveResourcesFindIpList() {
        return new ActiveResources.FindIpList();
    }

    /**
     * Create an instance of {@link BasicInfo.UpdateInfo.UpdateData.HouseInfo.IpSegInfo }
     * 
     */
    public BasicInfo.UpdateInfo.UpdateData.HouseInfo.IpSegInfo createBasicInfoUpdateInfoUpdateDataHouseInfoIpSegInfo() {
        return new BasicInfo.UpdateInfo.UpdateData.HouseInfo.IpSegInfo();
    }

    /**
     * Create an instance of {@link UploadRecordData }
     * 
     */
    public UploadRecordData createUploadRecordData() {
        return new UploadRecordData();
    }

    /**
     * Create an instance of {@link BasicInfo.NewInfo.HouseInfo.IpSegInfo }
     * 
     */
    public BasicInfo.NewInfo.HouseInfo.IpSegInfo createBasicInfoNewInfoHouseInfoIpSegInfo() {
        return new BasicInfo.NewInfo.HouseInfo.IpSegInfo();
    }

    /**
     * Create an instance of {@link IDCTables.ResourceMonitoring.ResourceMonitorings.ProtocolIdentify }
     * 
     */
    public IDCTables.ResourceMonitoring.ResourceMonitorings.ProtocolIdentify createIDCTablesResourceMonitoringResourceMonitoringsProtocolIdentify() {
        return new IDCTables.ResourceMonitoring.ResourceMonitorings.ProtocolIdentify();
    }

    /**
     * Create an instance of {@link BasicInfo.QueryResult.UserInfo.Info.ServiceInfo.HousesHoldInfo }
     * 
     */
    public BasicInfo.QueryResult.UserInfo.Info.ServiceInfo.HousesHoldInfo createBasicInfoQueryResultUserInfoInfoServiceInfoHousesHoldInfo() {
        return new BasicInfo.QueryResult.UserInfo.Info.ServiceInfo.HousesHoldInfo();
    }

    /**
     * Create an instance of {@link UploadRecordData.BaseInfo }
     * 
     */
    public UploadRecordData.BaseInfo createUploadRecordDataBaseInfo() {
        return new UploadRecordData.BaseInfo();
    }

    /**
     * Create an instance of {@link BasicInfo.UpdateInfo.UpdateData.HouseInfo.GatewayInfo }
     * 
     */
    public BasicInfo.UpdateInfo.UpdateData.HouseInfo.GatewayInfo createBasicInfoUpdateInfoUpdateDataHouseInfoGatewayInfo() {
        return new BasicInfo.UpdateInfo.UpdateData.HouseInfo.GatewayInfo();
    }

    /**
     * Create an instance of {@link CodeList.Jfxz.JfxzXx }
     * 
     */
    public CodeList.Jfxz.JfxzXx createCodeListJfxzJfxzXx() {
        return new CodeList.Jfxz.JfxzXx();
    }

    /**
     * Create an instance of {@link UploadRecordData.BaseInfo.DomainInfo }
     * 
     */
    public UploadRecordData.BaseInfo.DomainInfo createUploadRecordDataBaseInfoDomainInfo() {
        return new UploadRecordData.BaseInfo.DomainInfo();
    }

    /**
     * Create an instance of {@link LogQueryResult.Result }
     * 
     */
    public LogQueryResult.Result createLogQueryResultResult() {
        return new LogQueryResult.Result();
    }

    /**
     * Create an instance of {@link BasicInfo.NewInfo.EmergencyContact }
     * 
     */
    public BasicInfo.NewInfo.EmergencyContact createBasicInfoNewInfoEmergencyContact() {
        return new BasicInfo.NewInfo.EmergencyContact();
    }

    /**
     * Create an instance of {@link com.aotain.smmsapi.task.bean.Command.Rule }
     * 
     */
    public com.aotain.smmsapi.task.bean.Command.Rule createCommandRule() {
        return new com.aotain.smmsapi.task.bean.Command.Rule();
    }

    /**
     * Create an instance of {@link UploadRecordData.RoomInfo.RoomsInfo.CabinetsInfo.PositionInfo.ServersInfo }
     * 
     */
    public UploadRecordData.RoomInfo.RoomsInfo.CabinetsInfo.PositionInfo.ServersInfo createUploadRecordDataRoomInfoRoomsInfoCabinetsInfoPositionInfoServersInfo() {
        return new UploadRecordData.RoomInfo.RoomsInfo.CabinetsInfo.PositionInfo.ServersInfo();
    }

    /**
     * Create an instance of {@link NoFilter }
     * 
     */
    public NoFilter createNoFilter() {
        return new NoFilter();
    }

    /**
     * Create an instance of {@link IDCTables.ResourceMonitoring.ResourceMonitorings.FindIpDomain }
     * 
     */
    public IDCTables.ResourceMonitoring.ResourceMonitorings.FindIpDomain createIDCTablesResourceMonitoringResourceMonitoringsFindIpDomain() {
        return new IDCTables.ResourceMonitoring.ResourceMonitorings.FindIpDomain();
    }

    /**
     * Create an instance of {@link BasicInfo.QueryResult.UserInfo.Info.HouseHoldInfo.IpSeg }
     * 
     */
    public BasicInfo.QueryResult.UserInfo.Info.HouseHoldInfo.IpSeg createBasicInfoQueryResultUserInfoInfoHouseHoldInfoIpSeg() {
        return new BasicInfo.QueryResult.UserInfo.Info.HouseHoldInfo.IpSeg();
    }

    /**
     * Create an instance of {@link CommandQueryResult.Command.Privilege }
     * 
     */
    public CommandQueryResult.Command.Privilege createCommandQueryResultCommandPrivilege() {
        return new CommandQueryResult.Command.Privilege();
    }

    /**
     * Create an instance of {@link BasicInfo.UpdateInfo.EmergencyContact }
     * 
     */
    public BasicInfo.UpdateInfo.EmergencyContact createBasicInfoUpdateInfoEmergencyContact() {
        return new BasicInfo.UpdateInfo.EmergencyContact();
    }

    /**
     * Create an instance of {@link Return }
     * 
     */
    public Return createReturn() {
        return new Return();
    }

    /**
     * Create an instance of {@link BasicInfo.QueryResult.HouseInfo.GatewayInfo }
     * 
     */
    public BasicInfo.QueryResult.HouseInfo.GatewayInfo createBasicInfoQueryResultHouseInfoGatewayInfo() {
        return new BasicInfo.QueryResult.HouseInfo.GatewayInfo();
    }

    /**
     * Create an instance of {@link LogQueryResult.Log }
     * 
     */
    public LogQueryResult.Log createLogQueryResultLog() {
        return new LogQueryResult.Log();
    }

    /**
     * Create an instance of {@link BasicInfo.UpdateInfo.UpdateData.UserInfo.Info.ServiceInfo.HousesHoldInfo.IpTrans.InternetIp }
     * 
     */
    public BasicInfo.UpdateInfo.UpdateData.UserInfo.Info.ServiceInfo.HousesHoldInfo.IpTrans.InternetIp createBasicInfoUpdateInfoUpdateDataUserInfoInfoServiceInfoHousesHoldInfoIpTransInternetIp() {
        return new BasicInfo.UpdateInfo.UpdateData.UserInfo.Info.ServiceInfo.HousesHoldInfo.IpTrans.InternetIp();
    }

    /**
     * Create an instance of {@link ReturnInfo.ReturnData }
     * 
     */
    public ReturnInfo.ReturnData createReturnInfoReturnData() {
        return new ReturnInfo.ReturnData();
    }

    /**
     * Create an instance of {@link BasicInfo.QueryResult.EmergencyContact }
     * 
     */
    public BasicInfo.QueryResult.EmergencyContact createBasicInfoQueryResultEmergencyContact() {
        return new BasicInfo.QueryResult.EmergencyContact();
    }

    /**
     * Create an instance of {@link LogQuery }
     * 
     */
    public LogQuery createLogQuery() {
        return new LogQuery();
    }

    /**
     * Create an instance of {@link CodeList.Basx }
     * 
     */
    public CodeList.Basx createCodeListBasx() {
        return new CodeList.Basx();
    }

    /**
     * Create an instance of {@link LogQuery.CommandInfo }
     * 
     */
    public LogQuery.CommandInfo createLogQueryCommandInfo() {
        return new LogQuery.CommandInfo();
    }

    /**
     * Create an instance of {@link BasicInfo.UpdateInfo.UpdateData.UserInfo.Info.ServiceInfo.HousesHoldInfo }
     * 
     */
    public BasicInfo.UpdateInfo.UpdateData.UserInfo.Info.ServiceInfo.HousesHoldInfo createBasicInfoUpdateInfoUpdateDataUserInfoInfoServiceInfoHousesHoldInfo() {
        return new BasicInfo.UpdateInfo.UpdateData.UserInfo.Info.ServiceInfo.HousesHoldInfo();
    }

    /**
     * Create an instance of {@link CommandQuery }
     * 
     */
    public CommandQuery createCommandQuery() {
        return new CommandQuery();
    }

    /**
     * Create an instance of {@link DomainVisitsAmount }
     * 
     */
    public DomainVisitsAmount createDomainVisitsAmount() {
        return new DomainVisitsAmount();
    }

    /**
     * Create an instance of {@link BasicInfo.UpdateInfo.IdcOfficer }
     * 
     */
    public BasicInfo.UpdateInfo.IdcOfficer createBasicInfoUpdateInfoIdcOfficer() {
        return new BasicInfo.UpdateInfo.IdcOfficer();
    }

    /**
     * Create an instance of {@link BasicInfo.NewInfo.HouseInfo }
     * 
     */
    public BasicInfo.NewInfo.HouseInfo createBasicInfoNewInfoHouseInfo() {
        return new BasicInfo.NewInfo.HouseInfo();
    }

    /**
     * Create an instance of {@link BasicInfo.QueryResult.HouseInfo }
     * 
     */
    public BasicInfo.QueryResult.HouseInfo createBasicInfoQueryResultHouseInfo() {
        return new BasicInfo.QueryResult.HouseInfo();
    }

    /**
     * Create an instance of {@link BasicInfo.UpdateInfo.UpdateData.HouseInfo.HouseOfficer }
     * 
     */
    public BasicInfo.UpdateInfo.UpdateData.HouseInfo.HouseOfficer createBasicInfoUpdateInfoUpdateDataHouseInfoHouseOfficer() {
        return new BasicInfo.UpdateInfo.UpdateData.HouseInfo.HouseOfficer();
    }

    /**
     * Create an instance of {@link com.aotain.smmsapi.task.bean.Command.Range }
     * 
     */
    public com.aotain.smmsapi.task.bean.Command.Range createCommandRange() {
        return new com.aotain.smmsapi.task.bean.Command.Range();
    }

    /**
     * Create an instance of {@link BasicInfo.QueryResult.UserInfo.Info.ServiceInfo.Domain }
     * 
     */
    public BasicInfo.QueryResult.UserInfo.Info.ServiceInfo.Domain createBasicInfoQueryResultUserInfoInfoServiceInfoDomain() {
        return new BasicInfo.QueryResult.UserInfo.Info.ServiceInfo.Domain();
    }

    /**
     * Create an instance of {@link FilterAmountData.FilterAmountDataList }
     * 
     */
    public FilterAmountData.FilterAmountDataList createFilterAmountDataFilterAmountDataList() {
        return new FilterAmountData.FilterAmountDataList();
    }

    /**
     * Create an instance of {@link com.aotain.smmsapi.task.bean.Command.Time }
     * 
     */
    public com.aotain.smmsapi.task.bean.Command.Time createCommandTime() {
        return new com.aotain.smmsapi.task.bean.Command.Time();
    }

    /**
     * Create an instance of {@link CodeList.Proapp }
     * 
     */
    public CodeList.Proapp createCodeListProapp() {
        return new CodeList.Proapp();
    }

    /**
     * Create an instance of {@link FilterAmountData }
     * 
     */
    public FilterAmountData createFilterAmountData() {
        return new FilterAmountData();
    }

    /**
     * Create an instance of {@link FilterResult }
     * 
     */
    public FilterResult createFilterResult() {
        return new FilterResult();
    }

    /**
     * Create an instance of {@link BasicInfo.UpdateInfo.UpdateData.UserInfo.Info.HouseHoldInfo.IpSeg }
     * 
     */
    public BasicInfo.UpdateInfo.UpdateData.UserInfo.Info.HouseHoldInfo.IpSeg createBasicInfoUpdateInfoUpdateDataUserInfoInfoHouseHoldInfoIpSeg() {
        return new BasicInfo.UpdateInfo.UpdateData.UserInfo.Info.HouseHoldInfo.IpSeg();
    }

    /**
     * Create an instance of {@link FilterResult.Log.Attachment }
     * 
     */
    public FilterResult.Log.Attachment createFilterResultLogAttachment() {
        return new FilterResult.Log.Attachment();
    }

    /**
     * Create an instance of {@link IDCTables.ResourceMonitoring }
     * 
     */
    public IDCTables.ResourceMonitoring createIDCTablesResourceMonitoring() {
        return new IDCTables.ResourceMonitoring();
    }

    /**
     * Create an instance of {@link IdcCommandAck }
     * 
     */
    public IdcCommandAck createIdcCommandAck() {
        return new IdcCommandAck();
    }

    /**
     * Create an instance of {@link BasicInfo.DeleteInfo.DeleteData.User.Service }
     * 
     */
    public BasicInfo.DeleteInfo.DeleteData.User.Service createBasicInfoDeleteInfoDeleteDataUserService() {
        return new BasicInfo.DeleteInfo.DeleteData.User.Service();
    }

    /**
     * Create an instance of {@link com.aotain.smmsapi.task.bean.Command.Action }
     * 
     */
    public com.aotain.smmsapi.task.bean.Command.Action createCommandAction() {
        return new com.aotain.smmsapi.task.bean.Command.Action();
    }

    /**
     * Create an instance of {@link CodeList.Jrfs }
     * 
     */
    public CodeList.Jrfs createCodeListJrfs() {
        return new CodeList.Jrfs();
    }

    /**
     * Create an instance of {@link FilterStatus }
     * 
     */
    public FilterStatus createFilterStatus() {
        return new FilterStatus();
    }

    /**
     * Create an instance of {@link MonitorResult.Log }
     * 
     */
    public MonitorResult.Log createMonitorResultLog() {
        return new MonitorResult.Log();
    }

    /**
     * Create an instance of {@link CodeList.Fwnr.FwnrXx }
     * 
     */
    public CodeList.Fwnr.FwnrXx createCodeListFwnrFwnrXx() {
        return new CodeList.Fwnr.FwnrXx();
    }

    /**
     * Create an instance of {@link UploadRecordData.BaseInfo.IpInfo }
     * 
     */
    public UploadRecordData.BaseInfo.IpInfo createUploadRecordDataBaseInfoIpInfo() {
        return new UploadRecordData.BaseInfo.IpInfo();
    }

    /**
     * Create an instance of {@link CommandQueryResult.Command }
     * 
     */
    public CommandQueryResult.Command createCommandQueryResultCommand() {
        return new CommandQueryResult.Command();
    }

    /**
     * Create an instance of {@link BasicInfo.DeleteInfo }
     * 
     */
    public BasicInfo.DeleteInfo createBasicInfoDeleteInfo() {
        return new BasicInfo.DeleteInfo();
    }

    /**
     * Create an instance of {@link BasicInfo }
     * 
     */
    public BasicInfo createBasicInfo() {
        return new BasicInfo();
    }

    /**
     * Create an instance of {@link CodeList.Qzsp }
     * 
     */
    public CodeList.Qzsp createCodeListQzsp() {
        return new CodeList.Qzsp();
    }

    /**
     * Create an instance of {@link DomainVisitsAmount.DomainVisitsAmountList }
     * 
     */
    public DomainVisitsAmount.DomainVisitsAmountList createDomainVisitsAmountDomainVisitsAmountList() {
        return new DomainVisitsAmount.DomainVisitsAmountList();
    }

    /**
     * Create an instance of {@link BasicInfo.QueryResult.HouseInfo.FrameInfo }
     * 
     */
    public BasicInfo.QueryResult.HouseInfo.FrameInfo createBasicInfoQueryResultHouseInfoFrameInfo() {
        return new BasicInfo.QueryResult.HouseInfo.FrameInfo();
    }

    /**
     * Create an instance of {@link BasicInfo.NewInfo.IdcOfficer }
     * 
     */
    public BasicInfo.NewInfo.IdcOfficer createBasicInfoNewInfoIdcOfficer() {
        return new BasicInfo.NewInfo.IdcOfficer();
    }

    /**
     * Create an instance of {@link ReturnInfo.ReturnData.User.Service }
     * 
     */
    public ReturnInfo.ReturnData.User.Service createReturnInfoReturnDataUserService() {
        return new ReturnInfo.ReturnData.User.Service();
    }

    /**
     * Create an instance of {@link CommandQueryResult.Command.Action }
     * 
     */
    public CommandQueryResult.Command.Action createCommandQueryResultCommandAction() {
        return new CommandQueryResult.Command.Action();
    }

    /**
     * Create an instance of {@link LogQueryResult }
     * 
     */
    public LogQueryResult createLogQueryResult() {
        return new LogQueryResult();
    }

    /**
     * Create an instance of {@link BasicInfo.QueryResult.HouseInfo.HouseOfficer }
     * 
     */
    public BasicInfo.QueryResult.HouseInfo.HouseOfficer createBasicInfoQueryResultHouseInfoHouseOfficer() {
        return new BasicInfo.QueryResult.HouseInfo.HouseOfficer();
    }

    /**
     * Create an instance of {@link IllegalWeb }
     * 
     */
    public IllegalWeb createIllegalWeb() {
        return new IllegalWeb();
    }

    /**
     * Create an instance of {@link CodeList.Qzsp.QzspXx }
     * 
     */
    public CodeList.Qzsp.QzspXx createCodeListQzspQzspXx() {
        return new CodeList.Qzsp.QzspXx();
    }

    /**
     * Create an instance of {@link CodeList.Urlcontent }
     * 
     */
    public CodeList.Urlcontent createCodeListUrlcontent() {
        return new CodeList.Urlcontent();
    }

    /**
     * Create an instance of {@link NetProtocolApp }
     * 
     */
    public NetProtocolApp createNetProtocolApp() {
        return new NetProtocolApp();
    }

    /**
     * Create an instance of {@link BasicInfo.NewInfo.UserInfo }
     * 
     */
    public BasicInfo.NewInfo.UserInfo createBasicInfoNewInfoUserInfo() {
        return new BasicInfo.NewInfo.UserInfo();
    }

    /**
     * Create an instance of {@link CodeList.Zjlx.ZjlxXx }
     * 
     */
    public CodeList.Zjlx.ZjlxXx createCodeListZjlxZjlxXx() {
        return new CodeList.Zjlx.ZjlxXx();
    }

    /**
     * Create an instance of {@link CommandQueryResult.Command.Rule }
     * 
     */
    public CommandQueryResult.Command.Rule createCommandQueryResultCommandRule() {
        return new CommandQueryResult.Command.Rule();
    }

    /**
     * Create an instance of {@link AreaControlPolicy }
     * 
     */
    public AreaControlPolicy createAreaControlPolicy() {
        return new AreaControlPolicy();
    }

    /**
     * Create an instance of {@link BasicInfo.NewInfo.UserInfo.Info.ServiceInfo.HousesHoldInfo }
     * 
     */
    public BasicInfo.NewInfo.UserInfo.Info.ServiceInfo.HousesHoldInfo createBasicInfoNewInfoUserInfoInfoServiceInfoHousesHoldInfo() {
        return new BasicInfo.NewInfo.UserInfo.Info.ServiceInfo.HousesHoldInfo();
    }

    /**
     * Create an instance of {@link CommandQueryResult.Command.Time }
     * 
     */
    public CommandQueryResult.Command.Time createCommandQueryResultCommandTime() {
        return new CommandQueryResult.Command.Time();
    }

    /**
     * Create an instance of {@link BasicInfo.DeleteInfo.DeleteData }
     * 
     */
    public BasicInfo.DeleteInfo.DeleteData createBasicInfoDeleteInfoDeleteData() {
        return new BasicInfo.DeleteInfo.DeleteData();
    }

    /**
     * Create an instance of {@link UploadRecordData.RoomInfo.RoomsInfo.CabinetsInfo }
     * 
     */
    public UploadRecordData.RoomInfo.RoomsInfo.CabinetsInfo createUploadRecordDataRoomInfoRoomsInfoCabinetsInfo() {
        return new UploadRecordData.RoomInfo.RoomsInfo.CabinetsInfo();
    }

    /**
     * Create an instance of {@link CommandQueryResult.Command.Range }
     * 
     */
    public CommandQueryResult.Command.Range createCommandQueryResultCommandRange() {
        return new CommandQueryResult.Command.Range();
    }

    /**
     * Create an instance of {@link UploadRecordData.RoomInfo.RoomsInfo.CabinetsInfo.PositionInfo }
     * 
     */
    public UploadRecordData.RoomInfo.RoomsInfo.CabinetsInfo.PositionInfo createUploadRecordDataRoomInfoRoomsInfoCabinetsInfoPositionInfo() {
        return new UploadRecordData.RoomInfo.RoomsInfo.CabinetsInfo.PositionInfo();
    }

    /**
     * Create an instance of {@link IdcMonitor.HouseMonitor }
     * 
     */
    public IdcMonitor.HouseMonitor createIdcMonitorHouseMonitor() {
        return new IdcMonitor.HouseMonitor();
    }

    /**
     * Create an instance of {@link BasicInfo.NewInfo.UserInfo.Info.HouseHoldInfo }
     * 
     */
    public BasicInfo.NewInfo.UserInfo.Info.HouseHoldInfo createBasicInfoNewInfoUserInfoInfoHouseHoldInfo() {
        return new BasicInfo.NewInfo.UserInfo.Info.HouseHoldInfo();
    }

    /**
     * Create an instance of {@link CodeList.Dwsx }
     * 
     */
    public CodeList.Dwsx createCodeListDwsx() {
        return new CodeList.Dwsx();
    }

    /**
     * Create an instance of {@link ActiveState }
     * 
     */
    public ActiveState createActiveState() {
        return new ActiveState();
    }

    /**
     * Create an instance of {@link BasicInfo.UpdateInfo.UpdateData.UserInfo.Info.ServiceInfo.HousesHoldInfo.VirtualServer }
     * 
     */
    public BasicInfo.UpdateInfo.UpdateData.UserInfo.Info.ServiceInfo.HousesHoldInfo.VirtualServer createBasicInfoUpdateInfoUpdateDataUserInfoInfoServiceInfoHousesHoldInfoVirtualServer() {
        return new BasicInfo.UpdateInfo.UpdateData.UserInfo.Info.ServiceInfo.HousesHoldInfo.VirtualServer();
    }

    /**
     * Create an instance of {@link BasicInfo.NewInfo.UserInfo.Info }
     * 
     */
    public BasicInfo.NewInfo.UserInfo.Info createBasicInfoNewInfoUserInfoInfo() {
        return new BasicInfo.NewInfo.UserInfo.Info();
    }

    /**
     * Create an instance of {@link CodeList.Wfwgqk }
     * 
     */
    public CodeList.Wfwgqk createCodeListWfwgqk() {
        return new CodeList.Wfwgqk();
    }

    /**
     * Create an instance of {@link BasicInfo.NewInfo.UserInfo.Info.ServiceInfo }
     * 
     */
    public BasicInfo.NewInfo.UserInfo.Info.ServiceInfo createBasicInfoNewInfoUserInfoInfoServiceInfo() {
        return new BasicInfo.NewInfo.UserInfo.Info.ServiceInfo();
    }

    /**
     * Create an instance of {@link BasicInfo.QueryResult.UserInfo }
     * 
     */
    public BasicInfo.QueryResult.UserInfo createBasicInfoQueryResultUserInfo() {
        return new BasicInfo.QueryResult.UserInfo();
    }

    /**
     * Create an instance of {@link BasicInfo.QueryResult }
     * 
     */
    public BasicInfo.QueryResult createBasicInfoQueryResult() {
        return new BasicInfo.QueryResult();
    }

    /**
     * Create an instance of {@link CodeList.Zjlx }
     * 
     */
    public CodeList.Zjlx createCodeListZjlx() {
        return new CodeList.Zjlx();
    }

    /**
     * Create an instance of {@link CodeList.Jfxz }
     * 
     */
    public CodeList.Jfxz createCodeListJfxz() {
        return new CodeList.Jfxz();
    }

    /**
     * Create an instance of {@link CommandRecord }
     * 
     */
    public CommandRecord createCommandRecord() {
        return new CommandRecord();
    }

    /**
     * Create an instance of {@link BasicInfo.NewInfo.UserInfo.Info.HouseHoldInfo.IpSeg }
     * 
     */
    public BasicInfo.NewInfo.UserInfo.Info.HouseHoldInfo.IpSeg createBasicInfoNewInfoUserInfoInfoHouseHoldInfoIpSeg() {
        return new BasicInfo.NewInfo.UserInfo.Info.HouseHoldInfo.IpSeg();
    }

    /**
     * Create an instance of {@link BasicInfo.NewInfo.UserInfo.Info.Officer }
     * 
     */
    public BasicInfo.NewInfo.UserInfo.Info.Officer createBasicInfoNewInfoUserInfoInfoOfficer() {
        return new BasicInfo.NewInfo.UserInfo.Info.Officer();
    }

    /**
     * Create an instance of {@link BasicInfo.UpdateInfo.UpdateData.UserInfo.Info.Officer }
     * 
     */
    public BasicInfo.UpdateInfo.UpdateData.UserInfo.Info.Officer createBasicInfoUpdateInfoUpdateDataUserInfoInfoOfficer() {
        return new BasicInfo.UpdateInfo.UpdateData.UserInfo.Info.Officer();
    }

    /**
     * Create an instance of {@link CodeList.Gzlx }
     * 
     */
    public CodeList.Gzlx createCodeListGzlx() {
        return new CodeList.Gzlx();
    }

    /**
     * Create an instance of {@link UploadRecordData.IcpInfo.IpIcpInfo }
     * 
     */
    public UploadRecordData.IcpInfo.IpIcpInfo createUploadRecordDataIcpInfoIpIcpInfo() {
        return new UploadRecordData.IcpInfo.IpIcpInfo();
    }

    /**
     * Create an instance of {@link BasicInfo.UpdateInfo.UpdateData.UserInfo.Info.ServiceInfo.HousesHoldInfo.IpTrans.NetIp }
     * 
     */
    public BasicInfo.UpdateInfo.UpdateData.UserInfo.Info.ServiceInfo.HousesHoldInfo.IpTrans.NetIp createBasicInfoUpdateInfoUpdateDataUserInfoInfoServiceInfoHousesHoldInfoIpTransNetIp() {
        return new BasicInfo.UpdateInfo.UpdateData.UserInfo.Info.ServiceInfo.HousesHoldInfo.IpTrans.NetIp();
    }

    /**
     * Create an instance of {@link FilterStatus.FilterStatusList }
     * 
     */
    public FilterStatus.FilterStatusList createFilterStatusFilterStatusList() {
        return new FilterStatus.FilterStatusList();
    }

    /**
     * Create an instance of {@link BasicInfo.UpdateInfo.UpdateData }
     * 
     */
    public BasicInfo.UpdateInfo.UpdateData createBasicInfoUpdateInfoUpdateData() {
        return new BasicInfo.UpdateInfo.UpdateData();
    }

    /**
     * Create an instance of {@link MonitorResult.Log.Attachment }
     * 
     */
    public MonitorResult.Log.Attachment createMonitorResultLogAttachment() {
        return new MonitorResult.Log.Attachment();
    }

    /**
     * Create an instance of {@link CommandQueryResult }
     * 
     */
    public CommandQueryResult createCommandQueryResult() {
        return new CommandQueryResult();
    }

    /**
     * Create an instance of {@link ReturnInfo.ReturnData.House }
     * 
     */
    public ReturnInfo.ReturnData.House createReturnInfoReturnDataHouse() {
        return new ReturnInfo.ReturnData.House();
    }

    /**
     * Create an instance of {@link UploadRecordData.IcpInfo }
     * 
     */
    public UploadRecordData.IcpInfo createUploadRecordDataIcpInfo() {
        return new UploadRecordData.IcpInfo();
    }

    /**
     * Create an instance of {@link BasicInfo.UpdateInfo.UpdateData.HouseInfo }
     * 
     */
    public BasicInfo.UpdateInfo.UpdateData.HouseInfo createBasicInfoUpdateInfoUpdateDataHouseInfo() {
        return new BasicInfo.UpdateInfo.UpdateData.HouseInfo();
    }

    /**
     * Create an instance of {@link com.aotain.smmsapi.task.bean.Command }
     * 
     */
    public com.aotain.smmsapi.task.bean.Command createCommand() {
        return new com.aotain.smmsapi.task.bean.Command();
    }

    /**
     * Create an instance of {@link BasicInfo.NewInfo }
     * 
     */
    public BasicInfo.NewInfo createBasicInfoNewInfo() {
        return new BasicInfo.NewInfo();
    }

    /**
     * Create an instance of {@link FileLoad }
     * 
     */
    public FileLoad createFileLoad() {
        return new FileLoad();
    }

    /**
     * Create an instance of {@link IdcCommandAck.CommandAck }
     * 
     */
    public IdcCommandAck.CommandAck createIdcCommandAckCommandAck() {
        return new IdcCommandAck.CommandAck();
    }

    /**
     * Create an instance of {@link BasicInfo.UpdateInfo.UpdateData.UserInfo }
     * 
     */
    public BasicInfo.UpdateInfo.UpdateData.UserInfo createBasicInfoUpdateInfoUpdateDataUserInfo() {
        return new BasicInfo.UpdateInfo.UpdateData.UserInfo();
    }

    /**
     * Create an instance of {@link Blacklist }
     * 
     */
    public Blacklist createBlacklist() {
        return new Blacklist();
    }

    /**
     * Create an instance of {@link BasicInfo.NewInfo.UserInfo.Info.ServiceInfo.HousesHoldInfo.IpTrans.InternetIp }
     * 
     */
    public BasicInfo.NewInfo.UserInfo.Info.ServiceInfo.HousesHoldInfo.IpTrans.InternetIp createBasicInfoNewInfoUserInfoInfoServiceInfoHousesHoldInfoIpTransInternetIp() {
        return new BasicInfo.NewInfo.UserInfo.Info.ServiceInfo.HousesHoldInfo.IpTrans.InternetIp();
    }

    /**
     * Create an instance of {@link BasicInfo.NewInfo.UserInfo.Info.ServiceInfo.HousesHoldInfo.IpTrans.NetIp }
     * 
     */
    public BasicInfo.NewInfo.UserInfo.Info.ServiceInfo.HousesHoldInfo.IpTrans.NetIp createBasicInfoNewInfoUserInfoInfoServiceInfoHousesHoldInfoIpTransNetIp() {
        return new BasicInfo.NewInfo.UserInfo.Info.ServiceInfo.HousesHoldInfo.IpTrans.NetIp();
    }

    /**
     * Create an instance of {@link ReturnInfo }
     * 
     */
    public ReturnInfo createReturnInfo() {
        return new ReturnInfo();
    }

    /**
     * Create an instance of {@link IDCTables.ResourceMonitoring.ResourceMonitorings.FindTopDomainList }
     * 
     */
    public IDCTables.ResourceMonitoring.ResourceMonitorings.FindTopDomainList createIDCTablesResourceMonitoringResourceMonitoringsFindTopDomainList() {
        return new IDCTables.ResourceMonitoring.ResourceMonitorings.FindTopDomainList();
    }

    /**
     * Create an instance of {@link BasicInfo.NewInfo.UserInfo.Info.ServiceInfo.HousesHoldInfo.VirtualServer }
     * 
     */
    public BasicInfo.NewInfo.UserInfo.Info.ServiceInfo.HousesHoldInfo.VirtualServer createBasicInfoNewInfoUserInfoInfoServiceInfoHousesHoldInfoVirtualServer() {
        return new BasicInfo.NewInfo.UserInfo.Info.ServiceInfo.HousesHoldInfo.VirtualServer();
    }

    /**
     * Create an instance of {@link CodeList.Wfwgqk.WfwgqkXx }
     * 
     */
    public CodeList.Wfwgqk.WfwgqkXx createCodeListWfwgqkWfwgqkXx() {
        return new CodeList.Wfwgqk.WfwgqkXx();
    }

    /**
     * Create an instance of {@link BasicInfo.QueryResult.UserInfo.Info.HouseHoldInfo }
     * 
     */
    public BasicInfo.QueryResult.UserInfo.Info.HouseHoldInfo createBasicInfoQueryResultUserInfoInfoHouseHoldInfo() {
        return new BasicInfo.QueryResult.UserInfo.Info.HouseHoldInfo();
    }

    /**
     * Create an instance of {@link QueryView }
     * 
     */
    public QueryView createQueryView() {
        return new QueryView();
    }

    /**
     * Create an instance of {@link BasicInfo.UpdateInfo.UpdateData.UserInfo.Info.ServiceInfo }
     * 
     */
    public BasicInfo.UpdateInfo.UpdateData.UserInfo.Info.ServiceInfo createBasicInfoUpdateInfoUpdateDataUserInfoInfoServiceInfo() {
        return new BasicInfo.UpdateInfo.UpdateData.UserInfo.Info.ServiceInfo();
    }

    /**
     * Create an instance of {@link BasicInfo.NewInfo.HouseInfo.FrameInfo }
     * 
     */
    public BasicInfo.NewInfo.HouseInfo.FrameInfo createBasicInfoNewInfoHouseInfoFrameInfo() {
        return new BasicInfo.NewInfo.HouseInfo.FrameInfo();
    }

    /**
     * Create an instance of {@link IDCTables.ResourceMonitoring.ResourceMonitorings.FindSubDoaminList }
     * 
     */
    public IDCTables.ResourceMonitoring.ResourceMonitorings.FindSubDoaminList createIDCTablesResourceMonitoringResourceMonitoringsFindSubDoaminList() {
        return new IDCTables.ResourceMonitoring.ResourceMonitorings.FindSubDoaminList();
    }

    /**
     * Create an instance of {@link BasicInfo.QueryResult.UserInfo.Info.Officer }
     * 
     */
    public BasicInfo.QueryResult.UserInfo.Info.Officer createBasicInfoQueryResultUserInfoInfoOfficer() {
        return new BasicInfo.QueryResult.UserInfo.Info.Officer();
    }

    /**
     * Create an instance of {@link CodeList.Basx.BasxXx }
     * 
     */
    public CodeList.Basx.BasxXx createCodeListBasxBasxXx() {
        return new CodeList.Basx.BasxXx();
    }

    /**
     * Create an instance of {@link ActiveResources }
     * 
     */
    public ActiveResources createActiveResources() {
        return new ActiveResources();
    }

    /**
     * Create an instance of {@link NetProtocolApp.NetProtocolAppList }
     * 
     */
    public NetProtocolApp.NetProtocolAppList createNetProtocolAppNetProtocolAppList() {
        return new NetProtocolApp.NetProtocolAppList();
    }

    /**
     * Create an instance of {@link BasicInfo.QueryResult.UserInfo.Info.ServiceInfo }
     * 
     */
    public BasicInfo.QueryResult.UserInfo.Info.ServiceInfo createBasicInfoQueryResultUserInfoInfoServiceInfo() {
        return new BasicInfo.QueryResult.UserInfo.Info.ServiceInfo();
    }

    /**
     * Create an instance of {@link IdcInfoManage.CommandInfo }
     * 
     */
    public IdcInfoManage.CommandInfo createIdcInfoManageCommandInfo() {
        return new IdcInfoManage.CommandInfo();
    }

    /**
     * Create an instance of {@link BasicInfo.DeleteInfo.DeleteData.User }
     * 
     */
    public BasicInfo.DeleteInfo.DeleteData.User createBasicInfoDeleteInfoDeleteDataUser() {
        return new BasicInfo.DeleteInfo.DeleteData.User();
    }

    /**
     * Create an instance of {@link IDCTables.ResourceMonitoring.ResourceMonitorings }
     * 
     */
    public IDCTables.ResourceMonitoring.ResourceMonitorings createIDCTablesResourceMonitoringResourceMonitorings() {
        return new IDCTables.ResourceMonitoring.ResourceMonitorings();
    }

    /**
     * Create an instance of {@link CodeList.Gzlx.GzlxXx }
     * 
     */
    public CodeList.Gzlx.GzlxXx createCodeListGzlxGzlxXx() {
        return new CodeList.Gzlx.GzlxXx();
    }

    /**
     * Create an instance of {@link CodeList.Dllx }
     * 
     */
    public CodeList.Dllx createCodeListDllx() {
        return new CodeList.Dllx();
    }

    /**
     * Create an instance of {@link IdcMonitor }
     * 
     */
    public IdcMonitor createIdcMonitor() {
        return new IdcMonitor();
    }

    /**
     * Create an instance of {@link BasicInfo.UpdateInfo.UpdateData.HouseInfo.FrameInfo }
     * 
     */
    public BasicInfo.UpdateInfo.UpdateData.HouseInfo.FrameInfo createBasicInfoUpdateInfoUpdateDataHouseInfoFrameInfo() {
        return new BasicInfo.UpdateInfo.UpdateData.HouseInfo.FrameInfo();
    }

    /**
     * Create an instance of {@link BasicInfo.UpdateInfo.UpdateData.UserInfo.Info }
     * 
     */
    public BasicInfo.UpdateInfo.UpdateData.UserInfo.Info createBasicInfoUpdateInfoUpdateDataUserInfoInfo() {
        return new BasicInfo.UpdateInfo.UpdateData.UserInfo.Info();
    }

    /**
     * Create an instance of {@link CodeList.Yyfwlx.YyfwlxXx }
     * 
     */
    public CodeList.Yyfwlx.YyfwlxXx createCodeListYyfwlxYyfwlxXx() {
        return new CodeList.Yyfwlx.YyfwlxXx();
    }

    /**
     * Create an instance of {@link LogQuery.CommandInfo.DestIp }
     * 
     */
    public LogQuery.CommandInfo.DestIp createLogQueryCommandInfoDestIp() {
        return new LogQuery.CommandInfo.DestIp();
    }

    /**
     * Create an instance of {@link LogQuery.CommandInfo.SrcIp }
     * 
     */
    public LogQuery.CommandInfo.SrcIp createLogQueryCommandInfoSrcIp() {
        return new LogQuery.CommandInfo.SrcIp();
    }

    /**
     * Create an instance of {@link BasicInfo.NewInfo.UserInfo.Info.ServiceInfo.Domain }
     * 
     */
    public BasicInfo.NewInfo.UserInfo.Info.ServiceInfo.Domain createBasicInfoNewInfoUserInfoInfoServiceInfoDomain() {
        return new BasicInfo.NewInfo.UserInfo.Info.ServiceInfo.Domain();
    }

    /**
     * Create an instance of {@link CodeList.Dwsx.DwsxXx }
     * 
     */
    public CodeList.Dwsx.DwsxXx createCodeListDwsxDwsxXx() {
        return new CodeList.Dwsx.DwsxXx();
    }

    /**
     * Create an instance of {@link BasicInfo.QueryResult.UserInfo.Info.ServiceInfo.HousesHoldInfo.IpTrans.InternetIp }
     * 
     */
    public BasicInfo.QueryResult.UserInfo.Info.ServiceInfo.HousesHoldInfo.IpTrans.InternetIp createBasicInfoQueryResultUserInfoInfoServiceInfoHousesHoldInfoIpTransInternetIp() {
        return new BasicInfo.QueryResult.UserInfo.Info.ServiceInfo.HousesHoldInfo.IpTrans.InternetIp();
    }

    /**
     * Create an instance of {@link com.aotain.smmsapi.task.bean.Command.Privilege }
     * 
     */
    public com.aotain.smmsapi.task.bean.Command.Privilege createCommandPrivilege() {
        return new com.aotain.smmsapi.task.bean.Command.Privilege();
    }

    /**
     * Create an instance of {@link BasicInfo.DeleteInfo.DeleteData.House }
     * 
     */
    public BasicInfo.DeleteInfo.DeleteData.House createBasicInfoDeleteInfoDeleteDataHouse() {
        return new BasicInfo.DeleteInfo.DeleteData.House();
    }

    /**
     * Create an instance of {@link ActiveResources.FindDomainList }
     * 
     */
    public ActiveResources.FindDomainList createActiveResourcesFindDomainList() {
        return new ActiveResources.FindDomainList();
    }

    /**
     * Create an instance of {@link BasicInfo.QueryResult.HouseInfo.IpSegInfo }
     * 
     */
    public BasicInfo.QueryResult.HouseInfo.IpSegInfo createBasicInfoQueryResultHouseInfoIpSegInfo() {
        return new BasicInfo.QueryResult.HouseInfo.IpSegInfo();
    }

    /**
     * Create an instance of {@link BasicInfo.NewInfo.HouseInfo.GatewayInfo }
     * 
     */
    public BasicInfo.NewInfo.HouseInfo.GatewayInfo createBasicInfoNewInfoHouseInfoGatewayInfo() {
        return new BasicInfo.NewInfo.HouseInfo.GatewayInfo();
    }

    /**
     * Create an instance of {@link CodeList.Proapp.ProappXx }
     * 
     */
    public CodeList.Proapp.ProappXx createCodeListProappProappXx() {
        return new CodeList.Proapp.ProappXx();
    }

    /**
     * Create an instance of {@link BasicInfo.NewInfo.HouseInfo.HouseOfficer }
     * 
     */
    public BasicInfo.NewInfo.HouseInfo.HouseOfficer createBasicInfoNewInfoHouseInfoHouseOfficer() {
        return new BasicInfo.NewInfo.HouseInfo.HouseOfficer();
    }

    /**
     * Create an instance of {@link IDCTables.ResourceMonitoring.ResourceMonitorings.FindIpList }
     * 
     */
    public IDCTables.ResourceMonitoring.ResourceMonitorings.FindIpList createIDCTablesResourceMonitoringResourceMonitoringsFindIpList() {
        return new IDCTables.ResourceMonitoring.ResourceMonitorings.FindIpList();
    }

    /**
     * Create an instance of {@link BasicInfo.NewInfo.UserInfo.Info.ServiceInfo.HousesHoldInfo.IpTrans }
     * 
     */
    public BasicInfo.NewInfo.UserInfo.Info.ServiceInfo.HousesHoldInfo.IpTrans createBasicInfoNewInfoUserInfoInfoServiceInfoHousesHoldInfoIpTrans() {
        return new BasicInfo.NewInfo.UserInfo.Info.ServiceInfo.HousesHoldInfo.IpTrans();
    }

    /**
     * Create an instance of {@link UploadRecordData.BaseInfo.DomainInfo.SubDomain }
     * 
     */
    public UploadRecordData.BaseInfo.DomainInfo.SubDomain createUploadRecordDataBaseInfoDomainInfoSubDomain() {
        return new UploadRecordData.BaseInfo.DomainInfo.SubDomain();
    }

    /**
     * Create an instance of {@link UploadRecordData.IcpInfo.DomainIcpInfo }
     * 
     */
    public UploadRecordData.IcpInfo.DomainIcpInfo createUploadRecordDataIcpInfoDomainIcpInfo() {
        return new UploadRecordData.IcpInfo.DomainIcpInfo();
    }

    /**
     * Create an instance of {@link CodeList.Jrfs.JrfsXx }
     * 
     */
    public CodeList.Jrfs.JrfsXx createCodeListJrfsJrfsXx() {
        return new CodeList.Jrfs.JrfsXx();
    }

    /**
     * Create an instance of {@link BasicInfo.QueryResult.IdcOfficer }
     * 
     */
    public BasicInfo.QueryResult.IdcOfficer createBasicInfoQueryResultIdcOfficer() {
        return new BasicInfo.QueryResult.IdcOfficer();
    }

    /**
     * Create an instance of {@link UploadRecordData.RoomInfo }
     * 
     */
    public UploadRecordData.RoomInfo createUploadRecordDataRoomInfo() {
        return new UploadRecordData.RoomInfo();
    }

    /**
     * Create an instance of {@link IdcMonitor.HouseMonitor.IpInfo }
     * 
     */
    public IdcMonitor.HouseMonitor.IpInfo createIdcMonitorHouseMonitorIpInfo() {
        return new IdcMonitor.HouseMonitor.IpInfo();
    }

    /**
     * Create an instance of {@link IdcMonitor.HouseMonitor.IllegalInfo }
     * 
     */
    public IdcMonitor.HouseMonitor.IllegalInfo createIdcMonitorHouseMonitorIllegalInfo() {
        return new IdcMonitor.HouseMonitor.IllegalInfo();
    }

    /**
     * Create an instance of {@link MonitorResult }
     * 
     */
    public MonitorResult createMonitorResult() {
        return new MonitorResult();
    }

    /**
     * Create an instance of {@link CodeList.Yyfwlx }
     * 
     */
    public CodeList.Yyfwlx createCodeListYyfwlx() {
        return new CodeList.Yyfwlx();
    }

    /**
     * Create an instance of {@link CodeList.Dllx.DllxXx }
     * 
     */
    public CodeList.Dllx.DllxXx createCodeListDllxDllxXx() {
        return new CodeList.Dllx.DllxXx();
    }

    /**
     * Create an instance of {@link ReturnInfo.ReturnData.User }
     * 
     */
    public ReturnInfo.ReturnData.User createReturnInfoReturnDataUser() {
        return new ReturnInfo.ReturnData.User();
    }

    /**
     * Create an instance of {@link BasicInfo.QueryResult.UserInfo.Info.ServiceInfo.HousesHoldInfo.VirtualServer }
     * 
     */
    public BasicInfo.QueryResult.UserInfo.Info.ServiceInfo.HousesHoldInfo.VirtualServer createBasicInfoQueryResultUserInfoInfoServiceInfoHousesHoldInfoVirtualServer() {
        return new BasicInfo.QueryResult.UserInfo.Info.ServiceInfo.HousesHoldInfo.VirtualServer();
    }

    /**
     * Create an instance of {@link BasicInfo.UpdateInfo.UpdateData.UserInfo.Info.HouseHoldInfo }
     * 
     */
    public BasicInfo.UpdateInfo.UpdateData.UserInfo.Info.HouseHoldInfo createBasicInfoUpdateInfoUpdateDataUserInfoInfoHouseHoldInfo() {
        return new BasicInfo.UpdateInfo.UpdateData.UserInfo.Info.HouseHoldInfo();
    }

    /**
     * Create an instance of {@link BasicInfo.UpdateInfo.UpdateData.UserInfo.Info.ServiceInfo.HousesHoldInfo.IpTrans }
     * 
     */
    public BasicInfo.UpdateInfo.UpdateData.UserInfo.Info.ServiceInfo.HousesHoldInfo.IpTrans createBasicInfoUpdateInfoUpdateDataUserInfoInfoServiceInfoHousesHoldInfoIpTrans() {
        return new BasicInfo.UpdateInfo.UpdateData.UserInfo.Info.ServiceInfo.HousesHoldInfo.IpTrans();
    }

    /**
     * Create an instance of {@link CodeList.Urlcontent.UrlcontentXx }
     * 
     */
    public CodeList.Urlcontent.UrlcontentXx createCodeListUrlcontentUrlcontentXx() {
        return new CodeList.Urlcontent.UrlcontentXx();
    }

    /**
     * Create an instance of {@link UploadRecordData.RoomInfo.RoomsInfo }
     * 
     */
    public UploadRecordData.RoomInfo.RoomsInfo createUploadRecordDataRoomInfoRoomsInfo() {
        return new UploadRecordData.RoomInfo.RoomsInfo();
    }

}
