
package com.aotain.smmsapi.task.client.cxf1;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2015-07-14T11:09:19.656+08:00
 * Generated source version: 2.7.12
 * 
 */
 
public class IdcWebService_IdcWebServicePort_Server{

    protected IdcWebService_IdcWebServicePort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new IdcWebServiceImpl();
        String address = "http://183.136.190.57:7080/ism/ws/commandack";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new IdcWebService_IdcWebServicePort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
